# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SlabWindow.ui'
#
# Created: Tue Dec 08 15:23:20 2015
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(999, 772)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 981, 681))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_monitor = QtGui.QWidget()
        self.tab_monitor.setObjectName(_fromUtf8("tab_monitor"))
        self.label_temp_MCCernox = QtGui.QLabel(self.tab_monitor)
        self.label_temp_MCCernox.setGeometry(QtCore.QRect(20, 330, 71, 16))
        self.label_temp_MCCernox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_temp_MCCernox.setObjectName(_fromUtf8("label_temp_MCCernox"))
        self.label_6 = QtGui.QLabel(self.tab_monitor)
        self.label_6.setGeometry(QtCore.QRect(260, 60, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_open_2 = QtGui.QPushButton(self.tab_monitor)
        self.pushButton_open_2.setGeometry(QtCore.QRect(260, 270, 40, 20))
        self.pushButton_open_2.setObjectName(_fromUtf8("pushButton_open_2"))
        self.label_7 = QtGui.QLabel(self.tab_monitor)
        self.label_7.setGeometry(QtCore.QRect(260, 110, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton_close_2 = QtGui.QPushButton(self.tab_monitor)
        self.pushButton_close_2.setGeometry(QtCore.QRect(300, 270, 40, 20))
        self.pushButton_close_2.setObjectName(_fromUtf8("pushButton_close_2"))
        self.label_8 = QtGui.QLabel(self.tab_monitor)
        self.label_8.setGeometry(QtCore.QRect(260, 160, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.line = QtGui.QFrame(self.tab_monitor)
        self.line.setGeometry(QtCore.QRect(257, 200, 181, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_pres_condense = QtGui.QLabel(self.tab_monitor)
        self.label_pres_condense.setGeometry(QtCore.QRect(260, 80, 101, 16))
        self.label_pres_condense.setObjectName(_fromUtf8("label_pres_condense"))
        self.label_10 = QtGui.QLabel(self.tab_monitor)
        self.label_10.setGeometry(QtCore.QRect(260, 220, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_pres_tank = QtGui.QLabel(self.tab_monitor)
        self.label_pres_tank.setGeometry(QtCore.QRect(260, 180, 71, 16))
        self.label_pres_tank.setObjectName(_fromUtf8("label_pres_tank"))
        self.label_pres_manifold = QtGui.QLabel(self.tab_monitor)
        self.label_pres_manifold.setGeometry(QtCore.QRect(260, 350, 46, 13))
        self.label_pres_manifold.setObjectName(_fromUtf8("label_pres_manifold"))
        self.label_pres_forepump = QtGui.QLabel(self.tab_monitor)
        self.label_pres_forepump.setGeometry(QtCore.QRect(260, 130, 91, 16))
        self.label_pres_forepump.setObjectName(_fromUtf8("label_pres_forepump"))
        self.label_status_1 = QtGui.QLabel(self.tab_monitor)
        self.label_status_1.setGeometry(QtCore.QRect(450, 240, 46, 21))
        self.label_status_1.setObjectName(_fromUtf8("label_status_1"))
        self.label_9 = QtGui.QLabel(self.tab_monitor)
        self.label_9.setGeometry(QtCore.QRect(260, 330, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.line_2 = QtGui.QFrame(self.tab_monitor)
        self.line_2.setGeometry(QtCore.QRect(200, 60, 20, 311))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtGui.QLabel(self.tab_monitor)
        self.label.setGeometry(QtCore.QRect(20, 260, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_status_2 = QtGui.QLabel(self.tab_monitor)
        self.label_status_2.setGeometry(QtCore.QRect(450, 270, 46, 21))
        self.label_status_2.setObjectName(_fromUtf8("label_status_2"))
        self.label_16 = QtGui.QLabel(self.tab_monitor)
        self.label_16.setGeometry(QtCore.QRect(20, 310, 151, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_temp_MCRuO2 = QtGui.QLabel(self.tab_monitor)
        self.label_temp_MCRuO2.setGeometry(QtCore.QRect(20, 280, 46, 13))
        self.label_temp_MCRuO2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_temp_MCRuO2.setObjectName(_fromUtf8("label_temp_MCRuO2"))
        self.label_status_3 = QtGui.QLabel(self.tab_monitor)
        self.label_status_3.setGeometry(QtCore.QRect(450, 300, 46, 21))
        self.label_status_3.setObjectName(_fromUtf8("label_status_3"))
        self.label_2 = QtGui.QLabel(self.tab_monitor)
        self.label_2.setGeometry(QtCore.QRect(20, 210, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_open_1 = QtGui.QPushButton(self.tab_monitor)
        self.pushButton_open_1.setGeometry(QtCore.QRect(260, 240, 40, 20))
        self.pushButton_open_1.setObjectName(_fromUtf8("pushButton_open_1"))
        self.pushButton_open_3 = QtGui.QPushButton(self.tab_monitor)
        self.pushButton_open_3.setGeometry(QtCore.QRect(260, 300, 40, 20))
        self.pushButton_open_3.setObjectName(_fromUtf8("pushButton_open_3"))
        self.label_3 = QtGui.QLabel(self.tab_monitor)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButton_close_1 = QtGui.QPushButton(self.tab_monitor)
        self.pushButton_close_1.setGeometry(QtCore.QRect(300, 240, 40, 20))
        self.pushButton_close_1.setObjectName(_fromUtf8("pushButton_close_1"))
        self.label_4 = QtGui.QLabel(self.tab_monitor)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_11 = QtGui.QLabel(self.tab_monitor)
        self.label_11.setGeometry(QtCore.QRect(350, 240, 71, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_temp_4K = QtGui.QLabel(self.tab_monitor)
        self.label_temp_4K.setGeometry(QtCore.QRect(20, 130, 46, 13))
        self.label_temp_4K.setObjectName(_fromUtf8("label_temp_4K"))
        self.label_5 = QtGui.QLabel(self.tab_monitor)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_temp_Still = QtGui.QLabel(self.tab_monitor)
        self.label_temp_Still.setGeometry(QtCore.QRect(20, 180, 46, 13))
        self.label_temp_Still.setObjectName(_fromUtf8("label_temp_Still"))
        self.label_12 = QtGui.QLabel(self.tab_monitor)
        self.label_12.setGeometry(QtCore.QRect(350, 270, 81, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_close_3 = QtGui.QPushButton(self.tab_monitor)
        self.pushButton_close_3.setGeometry(QtCore.QRect(300, 300, 40, 20))
        self.pushButton_close_3.setObjectName(_fromUtf8("pushButton_close_3"))
        self.label_temp_50K = QtGui.QLabel(self.tab_monitor)
        self.label_temp_50K.setGeometry(QtCore.QRect(20, 80, 46, 13))
        self.label_temp_50K.setObjectName(_fromUtf8("label_temp_50K"))
        self.label_temp_100mK = QtGui.QLabel(self.tab_monitor)
        self.label_temp_100mK.setGeometry(QtCore.QRect(20, 230, 46, 13))
        self.label_temp_100mK.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_temp_100mK.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_temp_100mK.setObjectName(_fromUtf8("label_temp_100mK"))
        self.label_13 = QtGui.QLabel(self.tab_monitor)
        self.label_13.setGeometry(QtCore.QRect(350, 300, 101, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_cleaning_status = QtGui.QLabel(self.tab_monitor)
        self.label_cleaning_status.setGeometry(QtCore.QRect(450, 20, 131, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_cleaning_status.setFont(font)
        self.label_cleaning_status.setObjectName(_fromUtf8("label_cleaning_status"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_monitor)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 20, 91, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.spinBox_noof_cleans = QtGui.QSpinBox(self.tab_monitor)
        self.spinBox_noof_cleans.setGeometry(QtCore.QRect(360, 20, 42, 22))
        self.spinBox_noof_cleans.setObjectName(_fromUtf8("spinBox_noof_cleans"))
        self.label_17 = QtGui.QLabel(self.tab_monitor)
        self.label_17.setGeometry(QtCore.QRect(410, 20, 41, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pushButton_CleanManifold = QtGui.QPushButton(self.tab_monitor)
        self.pushButton_CleanManifold.setGeometry(QtCore.QRect(260, 20, 91, 23))
        self.pushButton_CleanManifold.setObjectName(_fromUtf8("pushButton_CleanManifold"))
        self.textEdit_heman_logo = QtGui.QTextEdit(self.tab_monitor)
        self.textEdit_heman_logo.setGeometry(QtCore.QRect(580, 90, 225, 200))
        self.textEdit_heman_logo.setReadOnly(True)
        self.textEdit_heman_logo.setObjectName(_fromUtf8("textEdit_heman_logo"))
        self.tabWidget.addTab(self.tab_monitor, _fromUtf8(""))
        self.tab_graph = QtGui.QWidget()
        self.tab_graph.setObjectName(_fromUtf8("tab_graph"))
        self.lineEdit_totaltime = QtGui.QLineEdit(self.tab_graph)
        self.lineEdit_totaltime.setGeometry(QtCore.QRect(340, 10, 41, 20))
        self.lineEdit_totaltime.setInputMask(_fromUtf8(""))
        self.lineEdit_totaltime.setObjectName(_fromUtf8("lineEdit_totaltime"))
        self.curvewidget = CurveWidget(self.tab_graph)
        self.curvewidget.setGeometry(QtCore.QRect(20, 50, 900, 300))
        self.curvewidget.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget.setObjectName(_fromUtf8("curvewidget"))
        self.label_14 = QtGui.QLabel(self.tab_graph)
        self.label_14.setGeometry(QtCore.QRect(140, 10, 81, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.pushButton = QtGui.QPushButton(self.tab_graph)
        self.pushButton.setGeometry(QtCore.QRect(70, 10, 51, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_15 = QtGui.QLabel(self.tab_graph)
        self.label_15.setGeometry(QtCore.QRect(280, 10, 51, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit = QtGui.QLineEdit(self.tab_graph)
        self.lineEdit.setGeometry(QtCore.QRect(210, 11, 41, 20))
        self.lineEdit.setInputMask(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.tabWidget.addTab(self.tab_graph, _fromUtf8(""))
        self.tab_bncrf = QtGui.QWidget()
        self.tab_bncrf.setObjectName(_fromUtf8("tab_bncrf"))
        self.label_bncrf_status = QtGui.QLabel(self.tab_bncrf)
        self.label_bncrf_status.setGeometry(QtCore.QRect(110, 60, 151, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_status.setFont(font)
        self.label_bncrf_status.setObjectName(_fromUtf8("label_bncrf_status"))
        self.label_18 = QtGui.QLabel(self.tab_bncrf)
        self.label_18.setGeometry(QtCore.QRect(20, 60, 91, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.pushButton_bncrf_update = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_bncrf_update.setGeometry(QtCore.QRect(20, 20, 91, 23))
        self.pushButton_bncrf_update.setObjectName(_fromUtf8("pushButton_bncrf_update"))
        self.pushButton_plus10kHz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_plus10kHz.setGeometry(QtCore.QRect(360, 120, 61, 23))
        self.pushButton_plus10kHz.setObjectName(_fromUtf8("pushButton_plus10kHz"))
        self.pushButton_min10kHz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_min10kHz.setGeometry(QtCore.QRect(290, 120, 61, 23))
        self.pushButton_min10kHz.setObjectName(_fromUtf8("pushButton_min10kHz"))
        self.pushButton_plus1kHz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_plus1kHz.setGeometry(QtCore.QRect(360, 150, 61, 23))
        self.pushButton_plus1kHz.setObjectName(_fromUtf8("pushButton_plus1kHz"))
        self.pushButton_min1kHz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_min1kHz.setGeometry(QtCore.QRect(290, 150, 61, 23))
        self.pushButton_min1kHz.setObjectName(_fromUtf8("pushButton_min1kHz"))
        self.pushButton_plus100Hz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_plus100Hz.setGeometry(QtCore.QRect(360, 180, 61, 23))
        self.pushButton_plus100Hz.setObjectName(_fromUtf8("pushButton_plus100Hz"))
        self.pushButton_min100Hz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_min100Hz.setGeometry(QtCore.QRect(290, 180, 61, 23))
        self.pushButton_min100Hz.setObjectName(_fromUtf8("pushButton_min100Hz"))
        self.pushButton_plus100kHz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_plus100kHz.setGeometry(QtCore.QRect(360, 90, 61, 23))
        self.pushButton_plus100kHz.setObjectName(_fromUtf8("pushButton_plus100kHz"))
        self.pushButton_min100kHz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_min100kHz.setGeometry(QtCore.QRect(290, 90, 61, 23))
        self.pushButton_min100kHz.setObjectName(_fromUtf8("pushButton_min100kHz"))
        self.pushButton_plus1MHz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_plus1MHz.setGeometry(QtCore.QRect(360, 60, 61, 23))
        self.pushButton_plus1MHz.setObjectName(_fromUtf8("pushButton_plus1MHz"))
        self.pushButton_min1MHz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_min1MHz.setGeometry(QtCore.QRect(290, 60, 61, 23))
        self.pushButton_min1MHz.setObjectName(_fromUtf8("pushButton_min1MHz"))
        self.label_19 = QtGui.QLabel(self.tab_bncrf)
        self.label_19.setGeometry(QtCore.QRect(20, 100, 91, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_bncrf)
        self.label_20.setGeometry(QtCore.QRect(20, 80, 91, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_bncrf_output = QtGui.QLabel(self.tab_bncrf)
        self.label_bncrf_output.setGeometry(QtCore.QRect(110, 80, 151, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_output.setFont(font)
        self.label_bncrf_output.setText(_fromUtf8(""))
        self.label_bncrf_output.setObjectName(_fromUtf8("label_bncrf_output"))
        self.label_bncrf_frequency = QtGui.QLabel(self.tab_bncrf)
        self.label_bncrf_frequency.setGeometry(QtCore.QRect(110, 100, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency.setFont(font)
        self.label_bncrf_frequency.setText(_fromUtf8(""))
        self.label_bncrf_frequency.setObjectName(_fromUtf8("label_bncrf_frequency"))
        self.pushButton_plus10Hz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_plus10Hz.setGeometry(QtCore.QRect(360, 210, 61, 23))
        self.pushButton_plus10Hz.setObjectName(_fromUtf8("pushButton_plus10Hz"))
        self.pushButton_min10Hz = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_min10Hz.setGeometry(QtCore.QRect(290, 210, 61, 23))
        self.pushButton_min10Hz.setObjectName(_fromUtf8("pushButton_min10Hz"))
        self.curvewidget_bncrf_sweep = CurveWidget(self.tab_bncrf)
        self.curvewidget_bncrf_sweep.setGeometry(QtCore.QRect(30, 330, 900, 300))
        self.curvewidget_bncrf_sweep.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_bncrf_sweep.setObjectName(_fromUtf8("curvewidget_bncrf_sweep"))
        self.label_21 = QtGui.QLabel(self.tab_bncrf)
        self.label_21.setGeometry(QtCore.QRect(510, 10, 131, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_bncrf)
        self.label_22.setGeometry(QtCore.QRect(510, 110, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lineEdit_bncrf_sweep_center = QtGui.QLineEdit(self.tab_bncrf)
        self.lineEdit_bncrf_sweep_center.setGeometry(QtCore.QRect(510, 130, 111, 20))
        self.lineEdit_bncrf_sweep_center.setInputMask(_fromUtf8(""))
        self.lineEdit_bncrf_sweep_center.setObjectName(_fromUtf8("lineEdit_bncrf_sweep_center"))
        self.label_cleaning_status_5 = QtGui.QLabel(self.tab_bncrf)
        self.label_cleaning_status_5.setGeometry(QtCore.QRect(630, 130, 31, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_cleaning_status_5.setFont(font)
        self.label_cleaning_status_5.setObjectName(_fromUtf8("label_cleaning_status_5"))
        self.label_23 = QtGui.QLabel(self.tab_bncrf)
        self.label_23.setGeometry(QtCore.QRect(510, 160, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_bncrf_sweep_span = QtGui.QLineEdit(self.tab_bncrf)
        self.lineEdit_bncrf_sweep_span.setGeometry(QtCore.QRect(510, 180, 111, 20))
        self.lineEdit_bncrf_sweep_span.setInputMask(_fromUtf8(""))
        self.lineEdit_bncrf_sweep_span.setObjectName(_fromUtf8("lineEdit_bncrf_sweep_span"))
        self.label_cleaning_status_6 = QtGui.QLabel(self.tab_bncrf)
        self.label_cleaning_status_6.setGeometry(QtCore.QRect(630, 180, 31, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_cleaning_status_6.setFont(font)
        self.label_cleaning_status_6.setObjectName(_fromUtf8("label_cleaning_status_6"))
        self.pushButton_bncrf_sweep = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_bncrf_sweep.setGeometry(QtCore.QRect(510, 260, 91, 23))
        self.pushButton_bncrf_sweep.setObjectName(_fromUtf8("pushButton_bncrf_sweep"))
        self.label_24 = QtGui.QLabel(self.tab_bncrf)
        self.label_24.setGeometry(QtCore.QRect(510, 60, 131, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.combobox_alazar_range = QtGui.QComboBox(self.tab_bncrf)
        self.combobox_alazar_range.setGeometry(QtCore.QRect(510, 80, 69, 22))
        self.combobox_alazar_range.setObjectName(_fromUtf8("combobox_alazar_range"))
        self.combobox_alazar_range.addItem(_fromUtf8(""))
        self.combobox_alazar_range.addItem(_fromUtf8(""))
        self.combobox_alazar_range.addItem(_fromUtf8(""))
        self.combobox_alazar_range.addItem(_fromUtf8(""))
        self.combobox_alazar_range.addItem(_fromUtf8(""))
        self.combobox_alazar_range.addItem(_fromUtf8(""))
        self.combobox_alazar_range.addItem(_fromUtf8(""))
        self.combobox_alazar_channel = QtGui.QComboBox(self.tab_bncrf)
        self.combobox_alazar_channel.setGeometry(QtCore.QRect(510, 30, 31, 22))
        self.combobox_alazar_channel.setObjectName(_fromUtf8("combobox_alazar_channel"))
        self.combobox_alazar_channel.addItem(_fromUtf8(""))
        self.combobox_alazar_channel.addItem(_fromUtf8(""))
        self.pushButton_bncrf_output = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_bncrf_output.setGeometry(QtCore.QRect(310, 20, 91, 23))
        self.pushButton_bncrf_output.setObjectName(_fromUtf8("pushButton_bncrf_output"))
        self.label_bncrf_frequency_2 = QtGui.QLabel(self.tab_bncrf)
        self.label_bncrf_frequency_2.setGeometry(QtCore.QRect(190, 100, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_2.setFont(font)
        self.label_bncrf_frequency_2.setObjectName(_fromUtf8("label_bncrf_frequency_2"))
        self.label_25 = QtGui.QLabel(self.tab_bncrf)
        self.label_25.setGeometry(QtCore.QRect(20, 120, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.lineEdit_bncrf_quickset_frequency = QtGui.QLineEdit(self.tab_bncrf)
        self.lineEdit_bncrf_quickset_frequency.setGeometry(QtCore.QRect(20, 140, 111, 20))
        self.lineEdit_bncrf_quickset_frequency.setInputMask(_fromUtf8(""))
        self.lineEdit_bncrf_quickset_frequency.setObjectName(_fromUtf8("lineEdit_bncrf_quickset_frequency"))
        self.label_bncrf_frequency_3 = QtGui.QLabel(self.tab_bncrf)
        self.label_bncrf_frequency_3.setGeometry(QtCore.QRect(140, 140, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_3.setFont(font)
        self.label_bncrf_frequency_3.setObjectName(_fromUtf8("label_bncrf_frequency_3"))
        self.pushButton_set_bncrf_frequency = QtGui.QPushButton(self.tab_bncrf)
        self.pushButton_set_bncrf_frequency.setGeometry(QtCore.QRect(170, 140, 41, 21))
        self.pushButton_set_bncrf_frequency.setObjectName(_fromUtf8("pushButton_set_bncrf_frequency"))
        self.label_26 = QtGui.QLabel(self.tab_bncrf)
        self.label_26.setGeometry(QtCore.QRect(510, 210, 141, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lineEdit_bncrf_noofpoints = QtGui.QLineEdit(self.tab_bncrf)
        self.lineEdit_bncrf_noofpoints.setGeometry(QtCore.QRect(510, 230, 111, 20))
        self.lineEdit_bncrf_noofpoints.setInputMask(_fromUtf8(""))
        self.lineEdit_bncrf_noofpoints.setObjectName(_fromUtf8("lineEdit_bncrf_noofpoints"))
        self.line_7 = QtGui.QFrame(self.tab_bncrf)
        self.line_7.setGeometry(QtCore.QRect(240, 10, 20, 241))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.tab_bncrf)
        self.line_8.setGeometry(QtCore.QRect(460, 10, 20, 241))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.tabWidget.addTab(self.tab_bncrf, _fromUtf8(""))
        self.tab_bncawg = QtGui.QWidget()
        self.tab_bncawg.setObjectName(_fromUtf8("tab_bncawg"))
        self.pushButton_bncawg_update = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_bncawg_update.setGeometry(QtCore.QRect(20, 20, 91, 23))
        self.pushButton_bncawg_update.setObjectName(_fromUtf8("pushButton_bncawg_update"))
        self.lineEdit_bncawg_quickset_frequency = QtGui.QLineEdit(self.tab_bncawg)
        self.lineEdit_bncawg_quickset_frequency.setGeometry(QtCore.QRect(600, 60, 111, 20))
        self.lineEdit_bncawg_quickset_frequency.setInputMask(_fromUtf8(""))
        self.lineEdit_bncawg_quickset_frequency.setObjectName(_fromUtf8("lineEdit_bncawg_quickset_frequency"))
        self.label_bncrf_frequency_4 = QtGui.QLabel(self.tab_bncawg)
        self.label_bncrf_frequency_4.setGeometry(QtCore.QRect(720, 60, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_4.setFont(font)
        self.label_bncrf_frequency_4.setObjectName(_fromUtf8("label_bncrf_frequency_4"))
        self.label_27 = QtGui.QLabel(self.tab_bncawg)
        self.label_27.setGeometry(QtCore.QRect(500, 60, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_bncawg)
        self.label_28.setGeometry(QtCore.QRect(20, 100, 91, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_bncawg_frequency = QtGui.QLabel(self.tab_bncawg)
        self.label_bncawg_frequency.setGeometry(QtCore.QRect(110, 100, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncawg_frequency.setFont(font)
        self.label_bncawg_frequency.setText(_fromUtf8(""))
        self.label_bncawg_frequency.setObjectName(_fromUtf8("label_bncawg_frequency"))
        self.label_bncrf_frequency_6 = QtGui.QLabel(self.tab_bncawg)
        self.label_bncrf_frequency_6.setGeometry(QtCore.QRect(190, 100, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_6.setFont(font)
        self.label_bncrf_frequency_6.setObjectName(_fromUtf8("label_bncrf_frequency_6"))
        self.label_bncawg_output = QtGui.QLabel(self.tab_bncawg)
        self.label_bncawg_output.setGeometry(QtCore.QRect(110, 80, 151, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncawg_output.setFont(font)
        self.label_bncawg_output.setText(_fromUtf8(""))
        self.label_bncawg_output.setObjectName(_fromUtf8("label_bncawg_output"))
        self.label_29 = QtGui.QLabel(self.tab_bncawg)
        self.label_29.setGeometry(QtCore.QRect(20, 80, 91, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.tab_bncawg)
        self.label_30.setGeometry(QtCore.QRect(20, 60, 91, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_bncawg_status = QtGui.QLabel(self.tab_bncawg)
        self.label_bncawg_status.setGeometry(QtCore.QRect(110, 60, 151, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncawg_status.setFont(font)
        self.label_bncawg_status.setObjectName(_fromUtf8("label_bncawg_status"))
        self.pushButton_min10kHz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_min10kHz_2.setGeometry(QtCore.QRect(290, 120, 61, 23))
        self.pushButton_min10kHz_2.setObjectName(_fromUtf8("pushButton_min10kHz_2"))
        self.pushButton_plus1kHz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_plus1kHz_2.setGeometry(QtCore.QRect(360, 150, 61, 23))
        self.pushButton_plus1kHz_2.setObjectName(_fromUtf8("pushButton_plus1kHz_2"))
        self.pushButton_plus100kHz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_plus100kHz_2.setGeometry(QtCore.QRect(360, 90, 61, 23))
        self.pushButton_plus100kHz_2.setObjectName(_fromUtf8("pushButton_plus100kHz_2"))
        self.pushButton_plus100Hz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_plus100Hz_2.setGeometry(QtCore.QRect(360, 180, 61, 23))
        self.pushButton_plus100Hz_2.setObjectName(_fromUtf8("pushButton_plus100Hz_2"))
        self.pushButton_plus10kHz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_plus10kHz_2.setGeometry(QtCore.QRect(360, 120, 61, 23))
        self.pushButton_plus10kHz_2.setObjectName(_fromUtf8("pushButton_plus10kHz_2"))
        self.pushButton_bncawg_output = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_bncawg_output.setGeometry(QtCore.QRect(310, 20, 91, 23))
        self.pushButton_bncawg_output.setObjectName(_fromUtf8("pushButton_bncawg_output"))
        self.pushButton_plus10Hz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_plus10Hz_2.setGeometry(QtCore.QRect(360, 210, 61, 23))
        self.pushButton_plus10Hz_2.setObjectName(_fromUtf8("pushButton_plus10Hz_2"))
        self.pushButton_min10Hz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_min10Hz_2.setGeometry(QtCore.QRect(290, 210, 61, 23))
        self.pushButton_min10Hz_2.setObjectName(_fromUtf8("pushButton_min10Hz_2"))
        self.pushButton_min1MHz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_min1MHz_2.setGeometry(QtCore.QRect(290, 60, 61, 23))
        self.pushButton_min1MHz_2.setObjectName(_fromUtf8("pushButton_min1MHz_2"))
        self.pushButton_plus1MHz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_plus1MHz_2.setGeometry(QtCore.QRect(360, 60, 61, 23))
        self.pushButton_plus1MHz_2.setObjectName(_fromUtf8("pushButton_plus1MHz_2"))
        self.pushButton_min100kHz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_min100kHz_2.setGeometry(QtCore.QRect(290, 90, 61, 23))
        self.pushButton_min100kHz_2.setObjectName(_fromUtf8("pushButton_min100kHz_2"))
        self.pushButton_min100Hz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_min100Hz_2.setGeometry(QtCore.QRect(290, 180, 61, 23))
        self.pushButton_min100Hz_2.setObjectName(_fromUtf8("pushButton_min100Hz_2"))
        self.pushButton_min1kHz_2 = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_min1kHz_2.setGeometry(QtCore.QRect(290, 150, 61, 23))
        self.pushButton_min1kHz_2.setObjectName(_fromUtf8("pushButton_min1kHz_2"))
        self.label_33 = QtGui.QLabel(self.tab_bncawg)
        self.label_33.setGeometry(QtCore.QRect(500, 90, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.combobox_bncawg_waveform = QtGui.QComboBox(self.tab_bncawg)
        self.combobox_bncawg_waveform.setGeometry(QtCore.QRect(600, 90, 111, 22))
        self.combobox_bncawg_waveform.setObjectName(_fromUtf8("combobox_bncawg_waveform"))
        self.combobox_bncawg_waveform.addItem(_fromUtf8(""))
        self.combobox_bncawg_waveform.addItem(_fromUtf8(""))
        self.combobox_bncawg_waveform.addItem(_fromUtf8(""))
        self.combobox_bncawg_waveform.addItem(_fromUtf8(""))
        self.combobox_bncawg_waveform.addItem(_fromUtf8(""))
        self.combobox_bncawg_waveform.addItem(_fromUtf8(""))
        self.label_34 = QtGui.QLabel(self.tab_bncawg)
        self.label_34.setGeometry(QtCore.QRect(500, 120, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_bncrf_frequency_7 = QtGui.QLabel(self.tab_bncawg)
        self.label_bncrf_frequency_7.setGeometry(QtCore.QRect(720, 120, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_7.setFont(font)
        self.label_bncrf_frequency_7.setObjectName(_fromUtf8("label_bncrf_frequency_7"))
        self.lineEdit_bncawg_quickset_amplitude = QtGui.QLineEdit(self.tab_bncawg)
        self.lineEdit_bncawg_quickset_amplitude.setGeometry(QtCore.QRect(600, 120, 111, 20))
        self.lineEdit_bncawg_quickset_amplitude.setInputMask(_fromUtf8(""))
        self.lineEdit_bncawg_quickset_amplitude.setObjectName(_fromUtf8("lineEdit_bncawg_quickset_amplitude"))
        self.pushButton_bncawg_apply = QtGui.QPushButton(self.tab_bncawg)
        self.pushButton_bncawg_apply.setGeometry(QtCore.QRect(500, 210, 231, 23))
        self.pushButton_bncawg_apply.setObjectName(_fromUtf8("pushButton_bncawg_apply"))
        self.label_35 = QtGui.QLabel(self.tab_bncawg)
        self.label_35.setGeometry(QtCore.QRect(500, 150, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.lineEdit_bncawg_quickset_offset = QtGui.QLineEdit(self.tab_bncawg)
        self.lineEdit_bncawg_quickset_offset.setGeometry(QtCore.QRect(600, 150, 111, 20))
        self.lineEdit_bncawg_quickset_offset.setInputMask(_fromUtf8(""))
        self.lineEdit_bncawg_quickset_offset.setObjectName(_fromUtf8("lineEdit_bncawg_quickset_offset"))
        self.label_bncrf_frequency_8 = QtGui.QLabel(self.tab_bncawg)
        self.label_bncrf_frequency_8.setGeometry(QtCore.QRect(720, 150, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_8.setFont(font)
        self.label_bncrf_frequency_8.setObjectName(_fromUtf8("label_bncrf_frequency_8"))
        self.label_36 = QtGui.QLabel(self.tab_bncawg)
        self.label_36.setGeometry(QtCore.QRect(20, 120, 91, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.tab_bncawg)
        self.label_37.setGeometry(QtCore.QRect(20, 140, 91, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.tab_bncawg)
        self.label_38.setGeometry(QtCore.QRect(500, 180, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.lineEdit_bncawg_quickset_pulsewidth = QtGui.QLineEdit(self.tab_bncawg)
        self.lineEdit_bncawg_quickset_pulsewidth.setGeometry(QtCore.QRect(600, 180, 111, 20))
        self.lineEdit_bncawg_quickset_pulsewidth.setInputMask(_fromUtf8(""))
        self.lineEdit_bncawg_quickset_pulsewidth.setObjectName(_fromUtf8("lineEdit_bncawg_quickset_pulsewidth"))
        self.label_bncawg_amplitude = QtGui.QLabel(self.tab_bncawg)
        self.label_bncawg_amplitude.setGeometry(QtCore.QRect(110, 120, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncawg_amplitude.setFont(font)
        self.label_bncawg_amplitude.setText(_fromUtf8(""))
        self.label_bncawg_amplitude.setObjectName(_fromUtf8("label_bncawg_amplitude"))
        self.label_bncawg_offset = QtGui.QLabel(self.tab_bncawg)
        self.label_bncawg_offset.setGeometry(QtCore.QRect(110, 140, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncawg_offset.setFont(font)
        self.label_bncawg_offset.setText(_fromUtf8(""))
        self.label_bncawg_offset.setObjectName(_fromUtf8("label_bncawg_offset"))
        self.label_bncrf_frequency_9 = QtGui.QLabel(self.tab_bncawg)
        self.label_bncrf_frequency_9.setGeometry(QtCore.QRect(190, 120, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_9.setFont(font)
        self.label_bncrf_frequency_9.setObjectName(_fromUtf8("label_bncrf_frequency_9"))
        self.label_bncrf_frequency_10 = QtGui.QLabel(self.tab_bncawg)
        self.label_bncrf_frequency_10.setGeometry(QtCore.QRect(190, 140, 81, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_10.setFont(font)
        self.label_bncrf_frequency_10.setObjectName(_fromUtf8("label_bncrf_frequency_10"))
        self.label_nwa_save_name_2 = QtGui.QLabel(self.tab_bncawg)
        self.label_nwa_save_name_2.setGeometry(QtCore.QRect(720, 180, 271, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_nwa_save_name_2.setFont(font)
        self.label_nwa_save_name_2.setObjectName(_fromUtf8("label_nwa_save_name_2"))
        self.line_5 = QtGui.QFrame(self.tab_bncawg)
        self.line_5.setGeometry(QtCore.QRect(240, 10, 20, 241))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.tab_bncawg)
        self.line_6.setGeometry(QtCore.QRect(460, 10, 20, 241))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.tabWidget.addTab(self.tab_bncawg, _fromUtf8(""))
        self.tab_nwa = QtGui.QWidget()
        self.tab_nwa.setObjectName(_fromUtf8("tab_nwa"))
        self.lineEdit_nwa_savepath = QtGui.QLineEdit(self.tab_nwa)
        self.lineEdit_nwa_savepath.setGeometry(QtCore.QRect(320, 270, 451, 20))
        self.lineEdit_nwa_savepath.setObjectName(_fromUtf8("lineEdit_nwa_savepath"))
        self.label_31 = QtGui.QLabel(self.tab_nwa)
        self.label_31.setGeometry(QtCore.QRect(20, 30, 91, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.tab_nwa)
        self.label_32.setGeometry(QtCore.QRect(320, 250, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.pushButton_nwa_takesave = QtGui.QPushButton(self.tab_nwa)
        self.pushButton_nwa_takesave.setGeometry(QtCore.QRect(780, 270, 121, 21))
        self.pushButton_nwa_takesave.setObjectName(_fromUtf8("pushButton_nwa_takesave"))
        self.curvewidget_nwa = CurveWidget(self.tab_nwa)
        self.curvewidget_nwa.setGeometry(QtCore.QRect(30, 330, 900, 300))
        self.curvewidget_nwa.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_nwa.setObjectName(_fromUtf8("curvewidget_nwa"))
        self.label_nwa_status = QtGui.QLabel(self.tab_nwa)
        self.label_nwa_status.setGeometry(QtCore.QRect(100, 30, 151, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_nwa_status.setFont(font)
        self.label_nwa_status.setObjectName(_fromUtf8("label_nwa_status"))
        self.label_nwa_save_name = QtGui.QLabel(self.tab_nwa)
        self.label_nwa_save_name.setGeometry(QtCore.QRect(400, 290, 321, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_nwa_save_name.setFont(font)
        self.label_nwa_save_name.setObjectName(_fromUtf8("label_nwa_save_name"))
        self.lineEdit_nwa_center_or_start = QtGui.QLineEdit(self.tab_nwa)
        self.lineEdit_nwa_center_or_start.setGeometry(QtCore.QRect(120, 140, 111, 20))
        self.lineEdit_nwa_center_or_start.setInputMask(_fromUtf8(""))
        self.lineEdit_nwa_center_or_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_nwa_center_or_start.setObjectName(_fromUtf8("lineEdit_nwa_center_or_start"))
        self.comboBox_nwa_mode = QtGui.QComboBox(self.tab_nwa)
        self.comboBox_nwa_mode.setGeometry(QtCore.QRect(120, 110, 111, 22))
        self.comboBox_nwa_mode.setObjectName(_fromUtf8("comboBox_nwa_mode"))
        self.comboBox_nwa_mode.addItem(_fromUtf8(""))
        self.comboBox_nwa_mode.addItem(_fromUtf8(""))
        self.label_nwa_mode = QtGui.QLabel(self.tab_nwa)
        self.label_nwa_mode.setGeometry(QtCore.QRect(20, 110, 91, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_nwa_mode.setFont(font)
        self.label_nwa_mode.setObjectName(_fromUtf8("label_nwa_mode"))
        self.label_nwa_center_or_start = QtGui.QLabel(self.tab_nwa)
        self.label_nwa_center_or_start.setGeometry(QtCore.QRect(20, 140, 91, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_nwa_center_or_start.setFont(font)
        self.label_nwa_center_or_start.setObjectName(_fromUtf8("label_nwa_center_or_start"))
        self.label_nwa_span_or_stop = QtGui.QLabel(self.tab_nwa)
        self.label_nwa_span_or_stop.setGeometry(QtCore.QRect(20, 170, 91, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_nwa_span_or_stop.setFont(font)
        self.label_nwa_span_or_stop.setObjectName(_fromUtf8("label_nwa_span_or_stop"))
        self.lineEdit_nwa_span_or_stop = QtGui.QLineEdit(self.tab_nwa)
        self.lineEdit_nwa_span_or_stop.setGeometry(QtCore.QRect(120, 170, 111, 20))
        self.lineEdit_nwa_span_or_stop.setInputMask(_fromUtf8(""))
        self.lineEdit_nwa_span_or_stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_nwa_span_or_stop.setObjectName(_fromUtf8("lineEdit_nwa_span_or_stop"))
        self.label_nwa_power = QtGui.QLabel(self.tab_nwa)
        self.label_nwa_power.setGeometry(QtCore.QRect(20, 200, 91, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_nwa_power.setFont(font)
        self.label_nwa_power.setObjectName(_fromUtf8("label_nwa_power"))
        self.label_nwa_ifbw = QtGui.QLabel(self.tab_nwa)
        self.label_nwa_ifbw.setGeometry(QtCore.QRect(20, 230, 91, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_nwa_ifbw.setFont(font)
        self.label_nwa_ifbw.setObjectName(_fromUtf8("label_nwa_ifbw"))
        self.lineEdit_nwa_power = QtGui.QLineEdit(self.tab_nwa)
        self.lineEdit_nwa_power.setGeometry(QtCore.QRect(120, 200, 111, 20))
        self.lineEdit_nwa_power.setInputMask(_fromUtf8(""))
        self.lineEdit_nwa_power.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_nwa_power.setObjectName(_fromUtf8("lineEdit_nwa_power"))
        self.lineEdit_nwa_ifbw = QtGui.QLineEdit(self.tab_nwa)
        self.lineEdit_nwa_ifbw.setGeometry(QtCore.QRect(120, 230, 111, 20))
        self.lineEdit_nwa_ifbw.setInputMask(_fromUtf8(""))
        self.lineEdit_nwa_ifbw.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_nwa_ifbw.setObjectName(_fromUtf8("lineEdit_nwa_ifbw"))
        self.label_bncrf_frequency_11 = QtGui.QLabel(self.tab_nwa)
        self.label_bncrf_frequency_11.setGeometry(QtCore.QRect(240, 170, 81, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_11.setFont(font)
        self.label_bncrf_frequency_11.setObjectName(_fromUtf8("label_bncrf_frequency_11"))
        self.label_bncrf_frequency_12 = QtGui.QLabel(self.tab_nwa)
        self.label_bncrf_frequency_12.setGeometry(QtCore.QRect(240, 200, 81, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_12.setFont(font)
        self.label_bncrf_frequency_12.setObjectName(_fromUtf8("label_bncrf_frequency_12"))
        self.label_bncrf_frequency_13 = QtGui.QLabel(self.tab_nwa)
        self.label_bncrf_frequency_13.setGeometry(QtCore.QRect(240, 230, 81, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_13.setFont(font)
        self.label_bncrf_frequency_13.setObjectName(_fromUtf8("label_bncrf_frequency_13"))
        self.label_nwa_points = QtGui.QLabel(self.tab_nwa)
        self.label_nwa_points.setGeometry(QtCore.QRect(20, 260, 91, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_nwa_points.setFont(font)
        self.label_nwa_points.setObjectName(_fromUtf8("label_nwa_points"))
        self.lineEdit_nwa_points = QtGui.QLineEdit(self.tab_nwa)
        self.lineEdit_nwa_points.setGeometry(QtCore.QRect(120, 260, 111, 20))
        self.lineEdit_nwa_points.setInputMask(_fromUtf8(""))
        self.lineEdit_nwa_points.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_nwa_points.setObjectName(_fromUtf8("lineEdit_nwa_points"))
        self.label_bncrf_frequency_14 = QtGui.QLabel(self.tab_nwa)
        self.label_bncrf_frequency_14.setGeometry(QtCore.QRect(240, 140, 81, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_bncrf_frequency_14.setFont(font)
        self.label_bncrf_frequency_14.setObjectName(_fromUtf8("label_bncrf_frequency_14"))
        self.label_nwa_avgs = QtGui.QLabel(self.tab_nwa)
        self.label_nwa_avgs.setGeometry(QtCore.QRect(20, 290, 91, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_nwa_avgs.setFont(font)
        self.label_nwa_avgs.setObjectName(_fromUtf8("label_nwa_avgs"))
        self.lineEdit_nwa_avgs = QtGui.QLineEdit(self.tab_nwa)
        self.lineEdit_nwa_avgs.setGeometry(QtCore.QRect(120, 290, 111, 20))
        self.lineEdit_nwa_avgs.setInputMask(_fromUtf8(""))
        self.lineEdit_nwa_avgs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_nwa_avgs.setObjectName(_fromUtf8("lineEdit_nwa_avgs"))
        self.label_nwa_measure = QtGui.QLabel(self.tab_nwa)
        self.label_nwa_measure.setGeometry(QtCore.QRect(20, 80, 91, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_nwa_measure.setFont(font)
        self.label_nwa_measure.setObjectName(_fromUtf8("label_nwa_measure"))
        self.comboBox_nwa_measure = QtGui.QComboBox(self.tab_nwa)
        self.comboBox_nwa_measure.setGeometry(QtCore.QRect(120, 80, 111, 22))
        self.comboBox_nwa_measure.setObjectName(_fromUtf8("comboBox_nwa_measure"))
        self.comboBox_nwa_measure.addItem(_fromUtf8(""))
        self.comboBox_nwa_measure.addItem(_fromUtf8(""))
        self.comboBox_nwa_measure.addItem(_fromUtf8(""))
        self.comboBox_nwa_measure.addItem(_fromUtf8(""))
        self.line_4 = QtGui.QFrame(self.tab_nwa)
        self.line_4.setGeometry(QtCore.QRect(20, 50, 231, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.textEdit_nwa = QtGui.QTextEdit(self.tab_nwa)
        self.textEdit_nwa.setGeometry(QtCore.QRect(320, 200, 451, 41))
        self.textEdit_nwa.setReadOnly(True)
        self.textEdit_nwa.setObjectName(_fromUtf8("textEdit_nwa"))
        self.label_39 = QtGui.QLabel(self.tab_nwa)
        self.label_39.setGeometry(QtCore.QRect(320, 290, 121, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.plainTextEdit_nwa_notes = QtGui.QPlainTextEdit(self.tab_nwa)
        self.plainTextEdit_nwa_notes.setGeometry(QtCore.QRect(320, 100, 451, 91))
        self.plainTextEdit_nwa_notes.setObjectName(_fromUtf8("plainTextEdit_nwa_notes"))
        self.label_nwa_measure_2 = QtGui.QLabel(self.tab_nwa)
        self.label_nwa_measure_2.setGeometry(QtCore.QRect(320, 70, 91, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_nwa_measure_2.setFont(font)
        self.label_nwa_measure_2.setObjectName(_fromUtf8("label_nwa_measure_2"))
        self.tabWidget.addTab(self.tab_nwa, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave = QtGui.QMenu(self.menuFile)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuInstruments = QtGui.QMenu(self.menubar)
        self.menuInstruments.setObjectName(_fromUtf8("menuInstruments"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuSweep = QtGui.QMenu(self.menubar)
        self.menuSweep.setObjectName(_fromUtf8("menuSweep"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExperimental_Settings = QtGui.QAction(MainWindow)
        self.actionExperimental_Settings.setObjectName(_fromUtf8("actionExperimental_Settings"))
        self.actionExperimental_and_Instrument_Settings = QtGui.QAction(MainWindow)
        self.actionExperimental_and_Instrument_Settings.setObjectName(_fromUtf8("actionExperimental_and_Instrument_Settings"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionHide_Message_Box = QtGui.QAction(MainWindow)
        self.actionHide_Message_Box.setCheckable(True)
        self.actionHide_Message_Box.setObjectName(_fromUtf8("actionHide_Message_Box"))
        self.actionHide_Progress_Bar = QtGui.QAction(MainWindow)
        self.actionHide_Progress_Bar.setCheckable(True)
        self.actionHide_Progress_Bar.setObjectName(_fromUtf8("actionHide_Progress_Bar"))
        self.actionStart_Sweep = QtGui.QAction(MainWindow)
        self.actionStart_Sweep.setObjectName(_fromUtf8("actionStart_Sweep"))
        self.param_abort_sweep = QtGui.QAction(MainWindow)
        self.param_abort_sweep.setObjectName(_fromUtf8("param_abort_sweep"))
        self.menuSave.addAction(self.actionExperimental_Settings)
        self.menuSave.addAction(self.actionExperimental_and_Instrument_Settings)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.actionLoad)
        self.menuView.addAction(self.actionHide_Message_Box)
        self.menuView.addAction(self.actionHide_Progress_Bar)
        self.menuSweep.addAction(self.actionStart_Sweep)
        self.menuSweep.addAction(self.param_abort_sweep)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInstruments.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSweep.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Cryo Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_temp_MCCernox.setText(QtGui.QApplication.translate("MainWindow", "MC Cernox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Condense pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_open_2.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Forepump pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_close_2.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Tank pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pres_condense.setText(QtGui.QApplication.translate("MainWindow", "0.000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Manifold status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pres_tank.setText(QtGui.QApplication.translate("MainWindow", "0.000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pres_manifold.setText(QtGui.QApplication.translate("MainWindow", "0.000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pres_forepump.setText(QtGui.QApplication.translate("MainWindow", "0.000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status_1.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Manifold pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Mixing Chamber (RuO2)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status_2.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Mixing Chamber (cernox)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_temp_MCRuO2.setText(QtGui.QApplication.translate("MainWindow", "MC RuO2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status_3.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "100 mK plate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_open_1.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_open_3.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Still", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_close_1.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "4K plate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Gas currently:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_temp_4K.setText(QtGui.QApplication.translate("MainWindow", "4K", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "50K plate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_temp_Still.setText(QtGui.QApplication.translate("MainWindow", "Still", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Pump currently:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_close_3.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label_temp_50K.setText(QtGui.QApplication.translate("MainWindow", "50K", None, QtGui.QApplication.UnicodeUTF8))
        self.label_temp_100mK.setText(QtGui.QApplication.translate("MainWindow", "100 mK", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Cryostat currently:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cleaning_status.setText(QtGui.QApplication.translate("MainWindow", "Cleaning", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Refresh values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "times", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CleanManifold.setText(QtGui.QApplication.translate("MainWindow", "Clean manifold", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_heman_logo.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_monitor), QtGui.QApplication.translate("MainWindow", "Fridge and manifold", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_totaltime.setText(QtGui.QApplication.translate("MainWindow", "10000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Refresh rate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Total time", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_graph), QtGui.QApplication.translate("MainWindow", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_status.setText(QtGui.QApplication.translate("MainWindow", "OK!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "BNC 845 status:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_bncrf_update.setText(QtGui.QApplication.translate("MainWindow", "Refresh values", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus10kHz.setText(QtGui.QApplication.translate("MainWindow", "+ 10 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min10kHz.setText(QtGui.QApplication.translate("MainWindow", "- 10 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus1kHz.setText(QtGui.QApplication.translate("MainWindow", "+ 1 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min1kHz.setText(QtGui.QApplication.translate("MainWindow", "- 1 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus100Hz.setText(QtGui.QApplication.translate("MainWindow", "+ 100 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min100Hz.setText(QtGui.QApplication.translate("MainWindow", "- 100 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus100kHz.setText(QtGui.QApplication.translate("MainWindow", "+ 100 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min100kHz.setText(QtGui.QApplication.translate("MainWindow", "- 100 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus1MHz.setText(QtGui.QApplication.translate("MainWindow", "+ 1 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min1MHz.setText(QtGui.QApplication.translate("MainWindow", "-1 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Frequency: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Output: ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus10Hz.setText(QtGui.QApplication.translate("MainWindow", "+ 10 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min10Hz.setText(QtGui.QApplication.translate("MainWindow", "- 10 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Sweep input channel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Sweep center frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_bncrf_sweep_center.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cleaning_status_5.setText(QtGui.QApplication.translate("MainWindow", "GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Sweep span", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_bncrf_sweep_span.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cleaning_status_6.setText(QtGui.QApplication.translate("MainWindow", "MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_bncrf_sweep.setText(QtGui.QApplication.translate("MainWindow", "Sweep it dude!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Channel range", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_alazar_range.setItemText(0, QtGui.QApplication.translate("MainWindow", "40 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_alazar_range.setItemText(1, QtGui.QApplication.translate("MainWindow", "100 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_alazar_range.setItemText(2, QtGui.QApplication.translate("MainWindow", "200 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_alazar_range.setItemText(3, QtGui.QApplication.translate("MainWindow", "400 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_alazar_range.setItemText(4, QtGui.QApplication.translate("MainWindow", "1 V", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_alazar_range.setItemText(5, QtGui.QApplication.translate("MainWindow", "2 V", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_alazar_range.setItemText(6, QtGui.QApplication.translate("MainWindow", "4 V", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_alazar_channel.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_alazar_channel.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_bncrf_output.setText(QtGui.QApplication.translate("MainWindow", "Toggle output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_2.setText(QtGui.QApplication.translate("MainWindow", "GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Quick set frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_bncrf_quickset_frequency.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_3.setText(QtGui.QApplication.translate("MainWindow", "GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_set_bncrf_frequency.setText(QtGui.QApplication.translate("MainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Sweep points", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_bncrf_noofpoints.setText(QtGui.QApplication.translate("MainWindow", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bncrf), QtGui.QApplication.translate("MainWindow", "BNC 845 RF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_bncawg_update.setText(QtGui.QApplication.translate("MainWindow", "Refresh values", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_bncawg_quickset_frequency.setText(QtGui.QApplication.translate("MainWindow", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_4.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Set frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Frequency: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_6.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Output: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "BNC status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncawg_status.setText(QtGui.QApplication.translate("MainWindow", "OK!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min10kHz_2.setText(QtGui.QApplication.translate("MainWindow", "- 10 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus1kHz_2.setText(QtGui.QApplication.translate("MainWindow", "+ 1 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus100kHz_2.setText(QtGui.QApplication.translate("MainWindow", "+ 100 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus100Hz_2.setText(QtGui.QApplication.translate("MainWindow", "+ 100 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus10kHz_2.setText(QtGui.QApplication.translate("MainWindow", "+ 10 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_bncawg_output.setText(QtGui.QApplication.translate("MainWindow", "Toggle output", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus10Hz_2.setText(QtGui.QApplication.translate("MainWindow", "+ 10 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min10Hz_2.setText(QtGui.QApplication.translate("MainWindow", "- 10 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min1MHz_2.setText(QtGui.QApplication.translate("MainWindow", "-1 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plus1MHz_2.setText(QtGui.QApplication.translate("MainWindow", "+ 1 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min100kHz_2.setText(QtGui.QApplication.translate("MainWindow", "- 100 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min100Hz_2.setText(QtGui.QApplication.translate("MainWindow", "- 100 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_min1kHz_2.setText(QtGui.QApplication.translate("MainWindow", "- 1 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Set wave form", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_bncawg_waveform.setItemText(0, QtGui.QApplication.translate("MainWindow", "SINE", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_bncawg_waveform.setItemText(1, QtGui.QApplication.translate("MainWindow", "PULSE", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_bncawg_waveform.setItemText(2, QtGui.QApplication.translate("MainWindow", "DC", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_bncawg_waveform.setItemText(3, QtGui.QApplication.translate("MainWindow", "SQUARE", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_bncawg_waveform.setItemText(4, QtGui.QApplication.translate("MainWindow", "RAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.combobox_bncawg_waveform.setItemText(5, QtGui.QApplication.translate("MainWindow", "NOISE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Set amplitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_7.setText(QtGui.QApplication.translate("MainWindow", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_bncawg_quickset_amplitude.setText(QtGui.QApplication.translate("MainWindow", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_bncawg_apply.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Set offset", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_bncawg_quickset_offset.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_8.setText(QtGui.QApplication.translate("MainWindow", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Amplitude: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Pulse duty cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_bncawg_quickset_pulsewidth.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_9.setText(QtGui.QApplication.translate("MainWindow", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_10.setText(QtGui.QApplication.translate("MainWindow", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_save_name_2.setText(QtGui.QApplication.translate("MainWindow", "Only applies if wave form is set to \"PULSE\"", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bncawg), QtGui.QApplication.translate("MainWindow", "BNC 50 MHz AWG", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nwa_savepath.setText(QtGui.QApplication.translate("MainWindow", "S:\\_Data\\150124 - M011 Helium Channels v5\\data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "NWA status: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Save path: ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_nwa_takesave.setText(QtGui.QApplication.translate("MainWindow", "Take and save trace", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_status.setText(QtGui.QApplication.translate("MainWindow", "OK!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_save_name.setText(QtGui.QApplication.translate("MainWindow", "Subfolder will be displayed here after first trace is taken", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nwa_center_or_start.setText(QtGui.QApplication.translate("MainWindow", "4500", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nwa_mode.setItemText(0, QtGui.QApplication.translate("MainWindow", "Center & span", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nwa_mode.setItemText(1, QtGui.QApplication.translate("MainWindow", "Start & stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_mode.setText(QtGui.QApplication.translate("MainWindow", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_center_or_start.setText(QtGui.QApplication.translate("MainWindow", "Center:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_span_or_stop.setText(QtGui.QApplication.translate("MainWindow", "Span: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nwa_span_or_stop.setText(QtGui.QApplication.translate("MainWindow", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_power.setText(QtGui.QApplication.translate("MainWindow", "Power:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_ifbw.setText(QtGui.QApplication.translate("MainWindow", "IFBW:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nwa_power.setText(QtGui.QApplication.translate("MainWindow", "-30", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nwa_ifbw.setText(QtGui.QApplication.translate("MainWindow", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_11.setText(QtGui.QApplication.translate("MainWindow", "MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_12.setText(QtGui.QApplication.translate("MainWindow", "dBm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_13.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_points.setText(QtGui.QApplication.translate("MainWindow", "Points:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nwa_points.setText(QtGui.QApplication.translate("MainWindow", "1601", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bncrf_frequency_14.setText(QtGui.QApplication.translate("MainWindow", "MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_avgs.setText(QtGui.QApplication.translate("MainWindow", "Averages:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_nwa_avgs.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_measure.setText(QtGui.QApplication.translate("MainWindow", "Measure:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nwa_measure.setItemText(0, QtGui.QApplication.translate("MainWindow", "S21", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nwa_measure.setItemText(1, QtGui.QApplication.translate("MainWindow", "S11", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nwa_measure.setItemText(2, QtGui.QApplication.translate("MainWindow", "S12", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_nwa_measure.setItemText(3, QtGui.QApplication.translate("MainWindow", "S22", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_nwa.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Data will be saved in subfolder with current date and current time in the directory below. Adjust all parameters below and then click &quot;Take and save trace&quot;</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "in subfolder", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit_nwa_notes.setPlainText(QtGui.QApplication.translate("MainWindow", "These notes will go in the datafile. For example: S21 of Niobium Cavity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nwa_measure_2.setText(QtGui.QApplication.translate("MainWindow", "Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_nwa), QtGui.QApplication.translate("MainWindow", "NWA basics", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("MainWindow", "Save..", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInstruments.setTitle(QtGui.QApplication.translate("MainWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSweep.setTitle(QtGui.QApplication.translate("MainWindow", "Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExperimental_Settings.setText(QtGui.QApplication.translate("MainWindow", "Experimental Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExperimental_and_Instrument_Settings.setText(QtGui.QApplication.translate("MainWindow", "Experimental and Instrument Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide_Message_Box.setText(QtGui.QApplication.translate("MainWindow", "Hide Message Box", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide_Progress_Bar.setText(QtGui.QApplication.translate("MainWindow", "Hide Progress Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_Sweep.setText(QtGui.QApplication.translate("MainWindow", "Start Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.param_abort_sweep.setText(QtGui.QApplication.translate("MainWindow", "Abort Sweep", None, QtGui.QApplication.UnicodeUTF8))

from guiqwt.plot import CurveWidget
