# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SlabWindow.ui'
#
# Created: Tue Jun 23 09:51:02 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(878, 470)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.curvewidget = CurveWidget(self.centralwidget)
        self.curvewidget.setGeometry(QtCore.QRect(39, 80, 421, 300))
        self.curvewidget.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget.setObjectName(_fromUtf8("curvewidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 40, 51, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 40, 61, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(480, 280, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_temp_MCRuO2 = QtGui.QLabel(self.centralwidget)
        self.label_temp_MCRuO2.setGeometry(QtCore.QRect(480, 300, 46, 13))
        self.label_temp_MCRuO2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_temp_MCRuO2.setObjectName(_fromUtf8("label_temp_MCRuO2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 230, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 180, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 130, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 80, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_temp_100mK = QtGui.QLabel(self.centralwidget)
        self.label_temp_100mK.setGeometry(QtCore.QRect(480, 250, 46, 13))
        self.label_temp_100mK.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_temp_100mK.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_temp_100mK.setObjectName(_fromUtf8("label_temp_100mK"))
        self.label_temp_Still = QtGui.QLabel(self.centralwidget)
        self.label_temp_Still.setGeometry(QtCore.QRect(480, 200, 46, 13))
        self.label_temp_Still.setObjectName(_fromUtf8("label_temp_Still"))
        self.label_temp_4K = QtGui.QLabel(self.centralwidget)
        self.label_temp_4K.setGeometry(QtCore.QRect(480, 150, 46, 13))
        self.label_temp_4K.setObjectName(_fromUtf8("label_temp_4K"))
        self.label_temp_50K = QtGui.QLabel(self.centralwidget)
        self.label_temp_50K.setGeometry(QtCore.QRect(480, 100, 46, 13))
        self.label_temp_50K.setObjectName(_fromUtf8("label_temp_50K"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(640, 80, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(640, 130, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(640, 180, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_pres_condense = QtGui.QLabel(self.centralwidget)
        self.label_pres_condense.setGeometry(QtCore.QRect(640, 100, 101, 16))
        self.label_pres_condense.setObjectName(_fromUtf8("label_pres_condense"))
        self.label_pres_forepump = QtGui.QLabel(self.centralwidget)
        self.label_pres_forepump.setGeometry(QtCore.QRect(640, 150, 91, 16))
        self.label_pres_forepump.setObjectName(_fromUtf8("label_pres_forepump"))
        self.label_pres_tank = QtGui.QLabel(self.centralwidget)
        self.label_pres_tank.setGeometry(QtCore.QRect(640, 200, 71, 16))
        self.label_pres_tank.setObjectName(_fromUtf8("label_pres_tank"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(637, 220, 121, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(610, 80, 20, 311))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(640, 350, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(640, 240, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_pres_manifold = QtGui.QLabel(self.centralwidget)
        self.label_pres_manifold.setGeometry(QtCore.QRect(640, 370, 46, 13))
        self.label_pres_manifold.setObjectName(_fromUtf8("label_pres_manifold"))
        self.label_status_1 = QtGui.QLabel(self.centralwidget)
        self.label_status_1.setGeometry(QtCore.QRect(830, 260, 46, 21))
        self.label_status_1.setObjectName(_fromUtf8("label_status_1"))
        self.label_status_2 = QtGui.QLabel(self.centralwidget)
        self.label_status_2.setGeometry(QtCore.QRect(830, 290, 46, 21))
        self.label_status_2.setObjectName(_fromUtf8("label_status_2"))
        self.label_status_3 = QtGui.QLabel(self.centralwidget)
        self.label_status_3.setGeometry(QtCore.QRect(830, 320, 46, 21))
        self.label_status_3.setObjectName(_fromUtf8("label_status_3"))
        self.pushButton_open_1 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_open_1.setGeometry(QtCore.QRect(640, 260, 40, 20))
        self.pushButton_open_1.setObjectName(_fromUtf8("pushButton_open_1"))
        self.pushButton_close_1 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_close_1.setGeometry(QtCore.QRect(680, 260, 40, 20))
        self.pushButton_close_1.setObjectName(_fromUtf8("pushButton_close_1"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(730, 260, 71, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(730, 290, 81, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(730, 320, 101, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.pushButton_open_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_open_2.setGeometry(QtCore.QRect(640, 290, 40, 20))
        self.pushButton_open_2.setObjectName(_fromUtf8("pushButton_open_2"))
        self.pushButton_open_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_open_3.setGeometry(QtCore.QRect(640, 320, 40, 20))
        self.pushButton_open_3.setObjectName(_fromUtf8("pushButton_open_3"))
        self.pushButton_close_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_close_3.setGeometry(QtCore.QRect(680, 320, 40, 20))
        self.pushButton_close_3.setObjectName(_fromUtf8("pushButton_close_3"))
        self.pushButton_close_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_close_2.setGeometry(QtCore.QRect(680, 290, 40, 20))
        self.pushButton_close_2.setObjectName(_fromUtf8("pushButton_close_2"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 41, 41, 20))
        self.lineEdit.setInputMask(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(150, 40, 81, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(290, 40, 51, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit_totaltime = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_totaltime.setGeometry(QtCore.QRect(350, 40, 41, 20))
        self.lineEdit_totaltime.setInputMask(_fromUtf8(""))
        self.lineEdit_totaltime.setObjectName(_fromUtf8("lineEdit_totaltime"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave = QtGui.QMenu(self.menuFile)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuInstruments = QtGui.QMenu(self.menubar)
        self.menuInstruments.setObjectName(_fromUtf8("menuInstruments"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuSweep = QtGui.QMenu(self.menubar)
        self.menuSweep.setObjectName(_fromUtf8("menuSweep"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExperimental_Settings = QtGui.QAction(MainWindow)
        self.actionExperimental_Settings.setObjectName(_fromUtf8("actionExperimental_Settings"))
        self.actionExperimental_and_Instrument_Settings = QtGui.QAction(MainWindow)
        self.actionExperimental_and_Instrument_Settings.setObjectName(_fromUtf8("actionExperimental_and_Instrument_Settings"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionHide_Message_Box = QtGui.QAction(MainWindow)
        self.actionHide_Message_Box.setCheckable(True)
        self.actionHide_Message_Box.setObjectName(_fromUtf8("actionHide_Message_Box"))
        self.actionHide_Progress_Bar = QtGui.QAction(MainWindow)
        self.actionHide_Progress_Bar.setCheckable(True)
        self.actionHide_Progress_Bar.setObjectName(_fromUtf8("actionHide_Progress_Bar"))
        self.actionStart_Sweep = QtGui.QAction(MainWindow)
        self.actionStart_Sweep.setObjectName(_fromUtf8("actionStart_Sweep"))
        self.param_abort_sweep = QtGui.QAction(MainWindow)
        self.param_abort_sweep.setObjectName(_fromUtf8("param_abort_sweep"))
        self.menuSave.addAction(self.actionExperimental_Settings)
        self.menuSave.addAction(self.actionExperimental_and_Instrument_Settings)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.actionLoad)
        self.menuView.addAction(self.actionHide_Message_Box)
        self.menuView.addAction(self.actionHide_Progress_Bar)
        self.menuSweep.addAction(self.actionStart_Sweep)
        self.menuSweep.addAction(self.param_abort_sweep)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInstruments.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSweep.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton.setText(_translate("MainWindow", "Run", None))
        self.pushButton_2.setText(_translate("MainWindow", "Refresh", None))
        self.label.setText(_translate("MainWindow", "Mixing Chamber plate", None))
        self.label_temp_MCRuO2.setText(_translate("MainWindow", "MC RuO2", None))
        self.label_2.setText(_translate("MainWindow", "100 mK plate", None))
        self.label_3.setText(_translate("MainWindow", "Still", None))
        self.label_4.setText(_translate("MainWindow", "4K plate", None))
        self.label_5.setText(_translate("MainWindow", "50K plate", None))
        self.label_temp_100mK.setText(_translate("MainWindow", "100 mK", None))
        self.label_temp_Still.setText(_translate("MainWindow", "Still", None))
        self.label_temp_4K.setText(_translate("MainWindow", "4K", None))
        self.label_temp_50K.setText(_translate("MainWindow", "50K", None))
        self.label_6.setText(_translate("MainWindow", "Condense pressure", None))
        self.label_7.setText(_translate("MainWindow", "Forepump pressure", None))
        self.label_8.setText(_translate("MainWindow", "Tank pressure", None))
        self.label_pres_condense.setText(_translate("MainWindow", "0.000", None))
        self.label_pres_forepump.setText(_translate("MainWindow", "0.000", None))
        self.label_pres_tank.setText(_translate("MainWindow", "0.000", None))
        self.label_9.setText(_translate("MainWindow", "Manifold pressure", None))
        self.label_10.setText(_translate("MainWindow", "Manifold status", None))
        self.label_pres_manifold.setText(_translate("MainWindow", "0.000", None))
        self.label_status_1.setText(_translate("MainWindow", "?", None))
        self.label_status_2.setText(_translate("MainWindow", "?", None))
        self.label_status_3.setText(_translate("MainWindow", "?", None))
        self.pushButton_open_1.setText(_translate("MainWindow", "Open", None))
        self.pushButton_close_1.setText(_translate("MainWindow", "Close", None))
        self.label_11.setText(_translate("MainWindow", "Gas currently:", None))
        self.label_12.setText(_translate("MainWindow", "Pump currently:", None))
        self.label_13.setText(_translate("MainWindow", "Cryostat currently:", None))
        self.pushButton_open_2.setText(_translate("MainWindow", "Open", None))
        self.pushButton_open_3.setText(_translate("MainWindow", "Open", None))
        self.pushButton_close_3.setText(_translate("MainWindow", "Close", None))
        self.pushButton_close_2.setText(_translate("MainWindow", "Close", None))
        self.lineEdit.setText(_translate("MainWindow", "5", None))
        self.label_14.setText(_translate("MainWindow", "Refresh rate", None))
        self.label_15.setText(_translate("MainWindow", "Total time", None))
        self.lineEdit_totaltime.setText(_translate("MainWindow", "10000", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSave.setTitle(_translate("MainWindow", "Save..", None))
        self.menuInstruments.setTitle(_translate("MainWindow", "Instruments", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuSweep.setTitle(_translate("MainWindow", "Sweep", None))
        self.actionExperimental_Settings.setText(_translate("MainWindow", "Experimental Settings", None))
        self.actionExperimental_and_Instrument_Settings.setText(_translate("MainWindow", "Experimental and Instrument Settings", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionHide_Message_Box.setText(_translate("MainWindow", "Hide Message Box", None))
        self.actionHide_Progress_Bar.setText(_translate("MainWindow", "Hide Progress Bar", None))
        self.actionStart_Sweep.setText(_translate("MainWindow", "Start Sweep", None))
        self.param_abort_sweep.setText(_translate("MainWindow", "Abort Sweep", None))

from guiqwt.plot import CurveWidget
