# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NWAWindow.ui'
#
# Created: Sat Dec 24 17:56:50 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_NWAWindow(object):
    def setupUi(self, NWAWindow):
        NWAWindow.setObjectName(_fromUtf8("NWAWindow"))
        NWAWindow.resize(1084, 748)
        self.centralwidget = QtGui.QWidget(NWAWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.centerstartLabel = QtGui.QLabel(self.groupBox)
        self.centerstartLabel.setObjectName(_fromUtf8("centerstartLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.centerstartLabel)
        self.spanstopLabel = QtGui.QLabel(self.groupBox)
        self.spanstopLabel.setObjectName(_fromUtf8("spanstopLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.spanstopLabel)
        self.powerSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.powerSpinBox.setMinimum(-100.0)
        self.powerSpinBox.setMaximum(10.0)
        self.powerSpinBox.setProperty(_fromUtf8("value"), -20.0)
        self.powerSpinBox.setObjectName(_fromUtf8("powerSpinBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.powerSpinBox)
        self.sweep_ptsSpinBox = QtGui.QSpinBox(self.groupBox)
        self.sweep_ptsSpinBox.setMaximum(1601)
        self.sweep_ptsSpinBox.setProperty(_fromUtf8("value"), 1601)
        self.sweep_ptsSpinBox.setObjectName(_fromUtf8("sweep_ptsSpinBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sweep_ptsSpinBox)
        self.ifbwSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.ifbwSpinBox.setMinimum(10.0)
        self.ifbwSpinBox.setMaximum(1000000.0)
        self.ifbwSpinBox.setProperty(_fromUtf8("value"), 1000.0)
        self.ifbwSpinBox.setObjectName(_fromUtf8("ifbwSpinBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ifbwSpinBox)
        self.avgsSpinBox = QtGui.QSpinBox(self.groupBox)
        self.avgsSpinBox.setMinimum(1)
        self.avgsSpinBox.setObjectName(_fromUtf8("avgsSpinBox"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.avgsSpinBox)
        self.centerstartSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.centerstartSpinBox.setDecimals(6)
        self.centerstartSpinBox.setMaximum(20.0)
        self.centerstartSpinBox.setSingleStep(0.1)
        self.centerstartSpinBox.setProperty(_fromUtf8("value"), 10.0)
        self.centerstartSpinBox.setObjectName(_fromUtf8("centerstartSpinBox"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.centerstartSpinBox)
        self.spanstopSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spanstopSpinBox.sizePolicy().hasHeightForWidth())
        self.spanstopSpinBox.setSizePolicy(sizePolicy)
        self.spanstopSpinBox.setMaximum(20000.0)
        self.spanstopSpinBox.setProperty(_fromUtf8("value"), 1000.0)
        self.spanstopSpinBox.setObjectName(_fromUtf8("spanstopSpinBox"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.spanstopSpinBox)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.resolutionSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.resolutionSpinBox.setDecimals(5)
        self.resolutionSpinBox.setMinimum(1e-05)
        self.resolutionSpinBox.setMaximum(999999999.0)
        self.resolutionSpinBox.setSingleStep(1e-05)
        self.resolutionSpinBox.setProperty(_fromUtf8("value"), 100.0)
        self.resolutionSpinBox.setObjectName(_fromUtf8("resolutionSpinBox"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.resolutionSpinBox)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.centerspanstartstopCheckBox = QtGui.QCheckBox(self.groupBox)
        self.centerspanstartstopCheckBox.setChecked(True)
        self.centerspanstartstopCheckBox.setObjectName(_fromUtf8("centerspanstartstopCheckBox"))
        self.verticalLayout_3.addWidget(self.centerspanstartstopCheckBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.go_button = QtGui.QPushButton(self.groupBox)
        self.go_button.setObjectName(_fromUtf8("go_button"))
        self.horizontalLayout_2.addWidget(self.go_button)
        self.abort_button = QtGui.QPushButton(self.groupBox)
        self.abort_button.setObjectName(_fromUtf8("abort_button"))
        self.horizontalLayout_2.addWidget(self.abort_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.datapathButton = QtGui.QPushButton(self.centralwidget)
        self.datapathButton.setObjectName(_fromUtf8("datapathButton"))
        self.horizontalLayout_3.addWidget(self.datapathButton)
        self.datapathLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.datapathLineEdit.setObjectName(_fromUtf8("datapathLineEdit"))
        self.horizontalLayout_3.addWidget(self.datapathLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.filenumberLabel = QtGui.QLabel(self.centralwidget)
        self.filenumberLabel.setObjectName(_fromUtf8("filenumberLabel"))
        self.horizontalLayout_6.addWidget(self.filenumberLabel)
        self.prefixLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.prefixLineEdit.setObjectName(_fromUtf8("prefixLineEdit"))
        self.horizontalLayout_6.addWidget(self.prefixLineEdit)
        self.saveCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.saveCheckBox.setObjectName(_fromUtf8("saveCheckBox"))
        self.horizontalLayout_6.addWidget(self.saveCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.magplotwidget = CurveWidget(self.centralwidget)
        self.magplotwidget.setOrientation(QtCore.Qt.Horizontal)
        self.magplotwidget.setObjectName(_fromUtf8("magplotwidget"))
        self.verticalLayout.addWidget(self.magplotwidget)
        self.phaseplotwidget = CurveWidget(self.centralwidget)
        self.phaseplotwidget.setOrientation(QtCore.Qt.Horizontal)
        self.phaseplotwidget.setObjectName(_fromUtf8("phaseplotwidget"))
        self.verticalLayout.addWidget(self.phaseplotwidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.message_box = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_box.sizePolicy().hasHeightForWidth())
        self.message_box.setSizePolicy(sizePolicy)
        self.message_box.setMaximumSize(QtCore.QSize(16777215, 80))
        self.message_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.message_box.setObjectName(_fromUtf8("message_box"))
        self.verticalLayout_2.addWidget(self.message_box)
        self.cmd_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.cmd_lineEdit.setObjectName(_fromUtf8("cmd_lineEdit"))
        self.verticalLayout_2.addWidget(self.cmd_lineEdit)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        NWAWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(NWAWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave = QtGui.QMenu(self.menuFile)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuInstruments = QtGui.QMenu(self.menubar)
        self.menuInstruments.setObjectName(_fromUtf8("menuInstruments"))
        NWAWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(NWAWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        NWAWindow.setStatusBar(self.statusbar)
        self.actionExperimental_Settings = QtGui.QAction(NWAWindow)
        self.actionExperimental_Settings.setObjectName(_fromUtf8("actionExperimental_Settings"))
        self.actionExperimental_and_Instrument_Settings = QtGui.QAction(NWAWindow)
        self.actionExperimental_and_Instrument_Settings.setObjectName(_fromUtf8("actionExperimental_and_Instrument_Settings"))
        self.actionLoad = QtGui.QAction(NWAWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.menuSave.addAction(self.actionExperimental_Settings)
        self.menuSave.addAction(self.actionExperimental_and_Instrument_Settings)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.actionLoad)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInstruments.menuAction())

        self.retranslateUi(NWAWindow)
        QtCore.QMetaObject.connectSlotsByName(NWAWindow)

    def retranslateUi(self, NWAWindow):
        NWAWindow.setWindowTitle(QtGui.QApplication.translate("NWAWindow", "Network Analyzer Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("NWAWindow", "NWA Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NWAWindow", "Power", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NWAWindow", "Sweep pts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NWAWindow", "IF BW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NWAWindow", "Avgs", None, QtGui.QApplication.UnicodeUTF8))
        self.centerstartLabel.setText(QtGui.QApplication.translate("NWAWindow", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.spanstopLabel.setText(QtGui.QApplication.translate("NWAWindow", "Span", None, QtGui.QApplication.UnicodeUTF8))
        self.powerSpinBox.setSuffix(QtGui.QApplication.translate("NWAWindow", " dBm", None, QtGui.QApplication.UnicodeUTF8))
        self.ifbwSpinBox.setSuffix(QtGui.QApplication.translate("NWAWindow", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.centerstartSpinBox.setSuffix(QtGui.QApplication.translate("NWAWindow", " GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.spanstopSpinBox.setSuffix(QtGui.QApplication.translate("NWAWindow", " MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("NWAWindow", "Max Step", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionSpinBox.setSuffix(QtGui.QApplication.translate("NWAWindow", " MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.centerspanstartstopCheckBox.setText(QtGui.QApplication.translate("NWAWindow", "Start/Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.go_button.setText(QtGui.QApplication.translate("NWAWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.abort_button.setText(QtGui.QApplication.translate("NWAWindow", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.datapathButton.setText(QtGui.QApplication.translate("NWAWindow", "Datapath", None, QtGui.QApplication.UnicodeUTF8))
        self.datapathLineEdit.setText(QtGui.QApplication.translate("NWAWindow", "S:\\_Data\\", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("NWAWindow", "File Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.filenumberLabel.setText(QtGui.QApplication.translate("NWAWindow", "000_", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixLineEdit.setText(QtGui.QApplication.translate("NWAWindow", "trace", None, QtGui.QApplication.UnicodeUTF8))
        self.saveCheckBox.setText(QtGui.QApplication.translate("NWAWindow", "Save Trace", None, QtGui.QApplication.UnicodeUTF8))
        self.message_box.setHtml(QtGui.QApplication.translate("NWAWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("NWAWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("NWAWindow", "Save..", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInstruments.setTitle(QtGui.QApplication.translate("NWAWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExperimental_Settings.setText(QtGui.QApplication.translate("NWAWindow", "Experimental Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExperimental_and_Instrument_Settings.setText(QtGui.QApplication.translate("NWAWindow", "Experimental and Instrument Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("NWAWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))

from guiqwt.plot import CurveWidget
