# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrum_analyzer.ui'
#
# Created: Fri Sep 09 21:34:31 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SpectrumAnalyzerWindow(object):
    def setupUi(self, SpectrumAnalyzerWindow):
        SpectrumAnalyzerWindow.setObjectName(_fromUtf8("SpectrumAnalyzerWindow"))
        SpectrumAnalyzerWindow.resize(813, 321)
        self.centralwidget = QtGui.QWidget(SpectrumAnalyzerWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.curvewidget = CurveWidget(self.centralwidget)
        self.curvewidget.setGeometry(QtCore.QRect(190, 10, 471, 251))
        self.curvewidget.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget.setObjectName(_fromUtf8("curvewidget"))
        self.clearButton = QtGui.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(680, 10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 164, 251))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.powerLCD = QtGui.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.powerLCD.setFont(font)
        self.powerLCD.setFrameShape(QtGui.QFrame.Panel)
        self.powerLCD.setFrameShadow(QtGui.QFrame.Raised)
        self.powerLCD.setLineWidth(1)
        self.powerLCD.setMidLineWidth(-2)
        self.powerLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.powerLCD.setObjectName(_fromUtf8("powerLCD"))
        self.verticalLayout.addWidget(self.powerLCD)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.instantRButton = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.instantRButton.setFont(font)
        self.instantRButton.setChecked(True)
        self.instantRButton.setObjectName(_fromUtf8("instantRButton"))
        self.powerReadingButtonGroup = QtGui.QButtonGroup(SpectrumAnalyzerWindow)
        self.powerReadingButtonGroup.setObjectName(_fromUtf8("powerReadingButtonGroup"))
        self.powerReadingButtonGroup.addButton(self.instantRButton)
        self.verticalLayout.addWidget(self.instantRButton)
        self.averageRButton = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.averageRButton.setFont(font)
        self.averageRButton.setObjectName(_fromUtf8("averageRButton"))
        self.powerReadingButtonGroup.addButton(self.averageRButton)
        self.verticalLayout.addWidget(self.averageRButton)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.updateRateSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.updateRateSpinBox.setFont(font)
        self.updateRateSpinBox.setMinimum(0.01)
        self.updateRateSpinBox.setMaximum(1000.0)
        self.updateRateSpinBox.setSingleStep(0.01)
        self.updateRateSpinBox.setObjectName(_fromUtf8("updateRateSpinBox"))
        self.horizontalLayout.addWidget(self.updateRateSpinBox)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        SpectrumAnalyzerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SpectrumAnalyzerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        SpectrumAnalyzerWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SpectrumAnalyzerWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SpectrumAnalyzerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SpectrumAnalyzerWindow)
        QtCore.QMetaObject.connectSlotsByName(SpectrumAnalyzerWindow)

    def retranslateUi(self, SpectrumAnalyzerWindow):
        SpectrumAnalyzerWindow.setWindowTitle(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Spectrum Analyzer", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Clear Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Current Power:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Power Reading Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.instantRButton.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Instant", None, QtGui.QApplication.UnicodeUTF8))
        self.averageRButton.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Average", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Update Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))

from guiqwt.plot import CurveWidget
