# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrum_analyzer_sweep.ui'
#
# Created: Mon Sep 19 17:04:14 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SpectrumAnalyzerWindow(object):
    def setupUi(self, SpectrumAnalyzerWindow):
        SpectrumAnalyzerWindow.setObjectName(_fromUtf8("SpectrumAnalyzerWindow"))
        SpectrumAnalyzerWindow.resize(817, 666)
        self.centralwidget = QtGui.QWidget(SpectrumAnalyzerWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.curvewidget = CurveWidget(self.centralwidget)
        self.curvewidget.setGeometry(QtCore.QRect(190, 10, 471, 301))
        self.curvewidget.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget.setObjectName(_fromUtf8("curvewidget"))
        self.clearButton = QtGui.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(680, 10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 176, 321))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.powerLCD = QtGui.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.powerLCD.setFont(font)
        self.powerLCD.setFrameShape(QtGui.QFrame.Panel)
        self.powerLCD.setFrameShadow(QtGui.QFrame.Raised)
        self.powerLCD.setLineWidth(1)
        self.powerLCD.setMidLineWidth(-2)
        self.powerLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.powerLCD.setObjectName(_fromUtf8("powerLCD"))
        self.horizontalLayout_6.addWidget(self.powerLCD)
        self.dBmLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dBmLabel.setFont(font)
        self.dBmLabel.setObjectName(_fromUtf8("dBmLabel"))
        self.horizontalLayout_6.addWidget(self.dBmLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.calibratedOuputCheckBox = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calibratedOuputCheckBox.setFont(font)
        self.calibratedOuputCheckBox.setObjectName(_fromUtf8("calibratedOuputCheckBox"))
        self.verticalLayout.addWidget(self.calibratedOuputCheckBox)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.frequencySpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frequencySpinBox.setFont(font)
        self.frequencySpinBox.setDecimals(5)
        self.frequencySpinBox.setMinimum(1.0)
        self.frequencySpinBox.setMaximum(10.0)
        self.frequencySpinBox.setSingleStep(0.01)
        self.frequencySpinBox.setProperty(_fromUtf8("value"), 7.000)
        self.frequencySpinBox.setObjectName(_fromUtf8("frequencySpinBox"))
        self.horizontalLayout_5.addWidget(self.frequencySpinBox)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_5.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.instantRButton = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.instantRButton.setFont(font)
        self.instantRButton.setChecked(True)
        self.instantRButton.setObjectName(_fromUtf8("instantRButton"))
        self.powerReadingButtonGroup = QtGui.QButtonGroup(SpectrumAnalyzerWindow)
        self.powerReadingButtonGroup.setObjectName(_fromUtf8("powerReadingButtonGroup"))
        self.powerReadingButtonGroup.addButton(self.instantRButton)
        self.verticalLayout.addWidget(self.instantRButton)
        self.averageRButton = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.averageRButton.setFont(font)
        self.averageRButton.setObjectName(_fromUtf8("averageRButton"))
        self.powerReadingButtonGroup.addButton(self.averageRButton)
        self.verticalLayout.addWidget(self.averageRButton)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.updateRateSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.updateRateSpinBox.setFont(font)
        self.updateRateSpinBox.setMinimum(0.01)
        self.updateRateSpinBox.setMaximum(30.0)
        self.updateRateSpinBox.setSingleStep(0.2)
        self.updateRateSpinBox.setObjectName(_fromUtf8("updateRateSpinBox"))
        self.horizontalLayout.addWidget(self.updateRateSpinBox)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.spectrumCurvewidget = CurveWidget(self.centralwidget)
        self.spectrumCurvewidget.setGeometry(QtCore.QRect(190, 350, 601, 251))
        self.spectrumCurvewidget.setOrientation(QtCore.Qt.Horizontal)
        self.spectrumCurvewidget.setObjectName(_fromUtf8("spectrumCurvewidget"))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 350, 161, 251))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.startSweepSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.startSweepSpinBox.setFont(font)
        self.startSweepSpinBox.setMinimum(1.0)
        self.startSweepSpinBox.setMaximum(10.0)
        self.startSweepSpinBox.setSingleStep(0.00001)
        self.startSweepSpinBox.setProperty(_fromUtf8("value"), 6.5)
        self.startSweepSpinBox.setObjectName(_fromUtf8("startSweepSpinBox"))
        self.horizontalLayout_2.addWidget(self.startSweepSpinBox)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.endSweepSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.endSweepSpinBox.setFont(font)
        self.endSweepSpinBox.setMinimum(1.0)
        self.endSweepSpinBox.setMaximum(10.0)
        self.endSweepSpinBox.setSingleStep(0.00001)
        self.endSweepSpinBox.setProperty(_fromUtf8("value"), 7.2)
        self.endSweepSpinBox.setObjectName(_fromUtf8("endSweepSpinBox"))
        self.horizontalLayout_3.addWidget(self.endSweepSpinBox)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.stepSweepSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stepSweepSpinBox.setFont(font)
        self.stepSweepSpinBox.setDecimals(6)
        self.stepSweepSpinBox.setMinimum(0.00001)
        self.stepSweepSpinBox.setMaximum(1.0)
        self.stepSweepSpinBox.setSingleStep(0.00001)
        self.stepSweepSpinBox.setProperty(_fromUtf8("value"), 0.005)
        self.stepSweepSpinBox.setObjectName(_fromUtf8("stepSweepSpinBox"))
        self.horizontalLayout_4.addWidget(self.stepSweepSpinBox)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.sweepButton = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sweepButton.setFont(font)
        self.sweepButton.setObjectName(_fromUtf8("sweepButton"))
        self.verticalLayout_2.addWidget(self.sweepButton)
        SpectrumAnalyzerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SpectrumAnalyzerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        SpectrumAnalyzerWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SpectrumAnalyzerWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SpectrumAnalyzerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SpectrumAnalyzerWindow)
        QtCore.QMetaObject.connectSlotsByName(SpectrumAnalyzerWindow)

    def retranslateUi(self, SpectrumAnalyzerWindow):
        SpectrumAnalyzerWindow.setWindowTitle(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Spectrum Analyzer", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Clear Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Current Power:", None, QtGui.QApplication.UnicodeUTF8))
        self.dBmLabel.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "(±0.2)dBm", None, QtGui.QApplication.UnicodeUTF8))
        self.calibratedOuputCheckBox.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Calibrated output (in dBm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "At Frequency:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Power Reading Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.instantRButton.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Instant", None, QtGui.QApplication.UnicodeUTF8))
        self.averageRButton.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Average", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Update Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Sweep Setup:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "End:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Step:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.sweepButton.setText(QtGui.QApplication.translate("SpectrumAnalyzerWindow", "Sweep", None, QtGui.QApplication.UnicodeUTF8))

from guiqwt.plot import CurveWidget
