# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlazarWidget.ui'
#
# Created: Sat Apr  7 13:18:28 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_AlazarForm(object):
    def setupUi(self, AlazarForm):
        AlazarForm.setObjectName(_fromUtf8("AlazarForm"))
        AlazarForm.resize(446, 678)
        AlazarForm.setWindowTitle(QtGui.QApplication.translate("AlazarForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.ScopeSettings = QtGui.QGroupBox(AlazarForm)
        self.ScopeSettings.setGeometry(QtCore.QRect(0, 0, 458, 661))
        self.ScopeSettings.setTitle(QtGui.QApplication.translate("AlazarForm", "Scope Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.ScopeSettings.setObjectName(_fromUtf8("ScopeSettings"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.ScopeSettings)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.SampleSettings = QtGui.QGroupBox(self.ScopeSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SampleSettings.sizePolicy().hasHeightForWidth())
        self.SampleSettings.setSizePolicy(sizePolicy)
        self.SampleSettings.setTitle(QtGui.QApplication.translate("AlazarForm", "Sample / Buffer Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.SampleSettings.setObjectName(_fromUtf8("SampleSettings"))
        self.gridLayout = QtGui.QGridLayout(self.SampleSettings)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.SampleSettings)
        self.label.setText(QtGui.QApplication.translate("AlazarForm", "Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.param_samplesPerRecord = QtGui.QSpinBox(self.SampleSettings)
        self.param_samplesPerRecord.setMinimum(32)
        self.param_samplesPerRecord.setMaximum(999999999)
        self.param_samplesPerRecord.setSingleStep(64)
        self.param_samplesPerRecord.setProperty("value", 1024)
        self.param_samplesPerRecord.setObjectName(_fromUtf8("param_samplesPerRecord"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.param_samplesPerRecord)
        self.label_2 = QtGui.QLabel(self.SampleSettings)
        self.label_2.setText(QtGui.QApplication.translate("AlazarForm", "Records per Buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.param_recordsPerBuffer = QtGui.QSpinBox(self.SampleSettings)
        self.param_recordsPerBuffer.setMinimum(1)
        self.param_recordsPerBuffer.setMaximum(999999999)
        self.param_recordsPerBuffer.setObjectName(_fromUtf8("param_recordsPerBuffer"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.param_recordsPerBuffer)
        self.label_3 = QtGui.QLabel(self.SampleSettings)
        self.label_3.setText(QtGui.QApplication.translate("AlazarForm", "Buffers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.param_bufferCount = QtGui.QSpinBox(self.SampleSettings)
        self.param_bufferCount.setMinimum(1)
        self.param_bufferCount.setMaximum(999999999)
        self.param_bufferCount.setObjectName(_fromUtf8("param_bufferCount"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.param_bufferCount)
        self.label_21 = QtGui.QLabel(self.SampleSettings)
        self.label_21.setText(QtGui.QApplication.translate("AlazarForm", "Records per Acquisition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_21)
        self.param_recordsPerAcquisition = QtGui.QSpinBox(self.SampleSettings)
        self.param_recordsPerAcquisition.setMinimum(1)
        self.param_recordsPerAcquisition.setMaximum(999999999)
        self.param_recordsPerAcquisition.setProperty("value", 1)
        self.param_recordsPerAcquisition.setObjectName(_fromUtf8("param_recordsPerAcquisition"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.param_recordsPerAcquisition)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_22 = QtGui.QLabel(self.SampleSettings)
        self.label_22.setText(QtGui.QApplication.translate("AlazarForm", "Excise Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_7.addWidget(self.label_22)
        self.param_excise_start = QtGui.QSpinBox(self.SampleSettings)
        self.param_excise_start.setObjectName(_fromUtf8("param_excise_start"))
        self.horizontalLayout_7.addWidget(self.param_excise_start)
        self.label_23 = QtGui.QLabel(self.SampleSettings)
        self.label_23.setText(QtGui.QApplication.translate("AlazarForm", "Excise End", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_7.addWidget(self.label_23)
        self.param_excise_end = QtGui.QSpinBox(self.SampleSettings)
        self.param_excise_end.setObjectName(_fromUtf8("param_excise_end"))
        self.horizontalLayout_7.addWidget(self.param_excise_end)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.SampleSettings)
        self.VerticalSettings = QtGui.QGroupBox(self.ScopeSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VerticalSettings.sizePolicy().hasHeightForWidth())
        self.VerticalSettings.setSizePolicy(sizePolicy)
        self.VerticalSettings.setTitle(QtGui.QApplication.translate("AlazarForm", "Vertical Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.VerticalSettings.setObjectName(_fromUtf8("VerticalSettings"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.VerticalSettings)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Ch1Vertical = QtGui.QGroupBox(self.VerticalSettings)
        self.Ch1Vertical.setTitle(QtGui.QApplication.translate("AlazarForm", "Channel 1", None, QtGui.QApplication.UnicodeUTF8))
        self.Ch1Vertical.setObjectName(_fromUtf8("Ch1Vertical"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Ch1Vertical)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.param_ch1_enabled = QtGui.QCheckBox(self.Ch1Vertical)
        self.param_ch1_enabled.setText(QtGui.QApplication.translate("AlazarForm", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch1_enabled.setChecked(True)
        self.param_ch1_enabled.setObjectName(_fromUtf8("param_ch1_enabled"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.param_ch1_enabled)
        self.param_ch1_filter = QtGui.QCheckBox(self.Ch1Vertical)
        self.param_ch1_filter.setText(QtGui.QApplication.translate("AlazarForm", "Filtered", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch1_filter.setObjectName(_fromUtf8("param_ch1_filter"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.param_ch1_filter)
        self.label_16 = QtGui.QLabel(self.Ch1Vertical)
        self.label_16.setText(QtGui.QApplication.translate("AlazarForm", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.param_ch1_range_txt = QtGui.QComboBox(self.Ch1Vertical)
        self.param_ch1_range_txt.setObjectName(_fromUtf8("param_ch1_range_txt"))
        self.param_ch1_range_txt.addItem(_fromUtf8(""))
        self.param_ch1_range_txt.setItemText(0, QtGui.QApplication.translate("AlazarForm", "4 V", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch1_range_txt.addItem(_fromUtf8(""))
        self.param_ch1_range_txt.setItemText(1, QtGui.QApplication.translate("AlazarForm", "2 V", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch1_range_txt.addItem(_fromUtf8(""))
        self.param_ch1_range_txt.setItemText(2, QtGui.QApplication.translate("AlazarForm", "1 V", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch1_range_txt.addItem(_fromUtf8(""))
        self.param_ch1_range_txt.setItemText(3, QtGui.QApplication.translate("AlazarForm", "400 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch1_range_txt.addItem(_fromUtf8(""))
        self.param_ch1_range_txt.setItemText(4, QtGui.QApplication.translate("AlazarForm", "200 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch1_range_txt.addItem(_fromUtf8(""))
        self.param_ch1_range_txt.setItemText(5, QtGui.QApplication.translate("AlazarForm", "100 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch1_range_txt.addItem(_fromUtf8(""))
        self.param_ch1_range_txt.setItemText(6, QtGui.QApplication.translate("AlazarForm", "40 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.param_ch1_range_txt)
        self.label_17 = QtGui.QLabel(self.Ch1Vertical)
        self.label_17.setText(QtGui.QApplication.translate("AlazarForm", "Coupling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.param_ch1_coupling = QtGui.QComboBox(self.Ch1Vertical)
        self.param_ch1_coupling.setObjectName(_fromUtf8("param_ch1_coupling"))
        self.param_ch1_coupling.addItem(_fromUtf8(""))
        self.param_ch1_coupling.setItemText(0, QtGui.QApplication.translate("AlazarForm", "DC", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch1_coupling.addItem(_fromUtf8(""))
        self.param_ch1_coupling.setItemText(1, QtGui.QApplication.translate("AlazarForm", "AC", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.param_ch1_coupling)
        self.verticalLayout_3.addLayout(self.formLayout_5)
        self.horizontalLayout_2.addWidget(self.Ch1Vertical)
        self.Ch2Vertical = QtGui.QGroupBox(self.VerticalSettings)
        self.Ch2Vertical.setTitle(QtGui.QApplication.translate("AlazarForm", "Channel 2", None, QtGui.QApplication.UnicodeUTF8))
        self.Ch2Vertical.setObjectName(_fromUtf8("Ch2Vertical"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Ch2Vertical)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.param_ch2_enabled = QtGui.QCheckBox(self.Ch2Vertical)
        self.param_ch2_enabled.setText(QtGui.QApplication.translate("AlazarForm", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch2_enabled.setChecked(True)
        self.param_ch2_enabled.setObjectName(_fromUtf8("param_ch2_enabled"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.param_ch2_enabled)
        self.param_ch2_filter = QtGui.QCheckBox(self.Ch2Vertical)
        self.param_ch2_filter.setText(QtGui.QApplication.translate("AlazarForm", "Filtered", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch2_filter.setObjectName(_fromUtf8("param_ch2_filter"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.param_ch2_filter)
        self.label_18 = QtGui.QLabel(self.Ch2Vertical)
        self.label_18.setText(QtGui.QApplication.translate("AlazarForm", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.param_ch2_range_txt = QtGui.QComboBox(self.Ch2Vertical)
        self.param_ch2_range_txt.setObjectName(_fromUtf8("param_ch2_range_txt"))
        self.param_ch2_range_txt.addItem(_fromUtf8(""))
        self.param_ch2_range_txt.setItemText(0, QtGui.QApplication.translate("AlazarForm", "4 V", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch2_range_txt.addItem(_fromUtf8(""))
        self.param_ch2_range_txt.setItemText(1, QtGui.QApplication.translate("AlazarForm", "2 V", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch2_range_txt.addItem(_fromUtf8(""))
        self.param_ch2_range_txt.setItemText(2, QtGui.QApplication.translate("AlazarForm", "1 V", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch2_range_txt.addItem(_fromUtf8(""))
        self.param_ch2_range_txt.setItemText(3, QtGui.QApplication.translate("AlazarForm", "400 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch2_range_txt.addItem(_fromUtf8(""))
        self.param_ch2_range_txt.setItemText(4, QtGui.QApplication.translate("AlazarForm", "200 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch2_range_txt.addItem(_fromUtf8(""))
        self.param_ch2_range_txt.setItemText(5, QtGui.QApplication.translate("AlazarForm", "100 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch2_range_txt.addItem(_fromUtf8(""))
        self.param_ch2_range_txt.setItemText(6, QtGui.QApplication.translate("AlazarForm", "40 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.param_ch2_range_txt)
        self.label_19 = QtGui.QLabel(self.Ch2Vertical)
        self.label_19.setText(QtGui.QApplication.translate("AlazarForm", "Coupling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.param_ch2_coupling = QtGui.QComboBox(self.Ch2Vertical)
        self.param_ch2_coupling.setObjectName(_fromUtf8("param_ch2_coupling"))
        self.param_ch2_coupling.addItem(_fromUtf8(""))
        self.param_ch2_coupling.setItemText(0, QtGui.QApplication.translate("AlazarForm", "DC", None, QtGui.QApplication.UnicodeUTF8))
        self.param_ch2_coupling.addItem(_fromUtf8(""))
        self.param_ch2_coupling.setItemText(1, QtGui.QApplication.translate("AlazarForm", "AC", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.param_ch2_coupling)
        self.verticalLayout_4.addLayout(self.formLayout_6)
        self.horizontalLayout_2.addWidget(self.Ch2Vertical)
        self.verticalLayout_5.addWidget(self.VerticalSettings)
        self.ClockSettings = QtGui.QGroupBox(self.ScopeSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClockSettings.sizePolicy().hasHeightForWidth())
        self.ClockSettings.setSizePolicy(sizePolicy)
        self.ClockSettings.setTitle(QtGui.QApplication.translate("AlazarForm", "Clock Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.ClockSettings.setObjectName(_fromUtf8("ClockSettings"))
        self.verticalLayout = QtGui.QVBoxLayout(self.ClockSettings)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_6 = QtGui.QLabel(self.ClockSettings)
        self.label_6.setText(QtGui.QApplication.translate("AlazarForm", "Clock Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.param_sample_rate_txt = QtGui.QComboBox(self.ClockSettings)
        self.param_sample_rate_txt.setObjectName(_fromUtf8("param_sample_rate_txt"))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(0, QtGui.QApplication.translate("AlazarForm", "1 GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(1, QtGui.QApplication.translate("AlazarForm", "500 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(2, QtGui.QApplication.translate("AlazarForm", "250 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(3, QtGui.QApplication.translate("AlazarForm", "100 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(4, QtGui.QApplication.translate("AlazarForm", "50 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(5, QtGui.QApplication.translate("AlazarForm", "20 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(6, QtGui.QApplication.translate("AlazarForm", "10 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(7, QtGui.QApplication.translate("AlazarForm", "5 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(8, QtGui.QApplication.translate("AlazarForm", "2 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(9, QtGui.QApplication.translate("AlazarForm", "1 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(10, QtGui.QApplication.translate("AlazarForm", "20 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(11, QtGui.QApplication.translate("AlazarForm", "10 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(12, QtGui.QApplication.translate("AlazarForm", "5 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(13, QtGui.QApplication.translate("AlazarForm", "2 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_sample_rate_txt.addItem(_fromUtf8(""))
        self.param_sample_rate_txt.setItemText(14, QtGui.QApplication.translate("AlazarForm", "1 kHz", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.param_sample_rate_txt)
        self.label_4 = QtGui.QLabel(self.ClockSettings)
        self.label_4.setText(QtGui.QApplication.translate("AlazarForm", "Clock Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.param_clock_source = QtGui.QComboBox(self.ClockSettings)
        self.param_clock_source.setObjectName(_fromUtf8("param_clock_source"))
        self.param_clock_source.addItem(_fromUtf8(""))
        self.param_clock_source.setItemText(0, QtGui.QApplication.translate("AlazarForm", "internal", None, QtGui.QApplication.UnicodeUTF8))
        self.param_clock_source.addItem(_fromUtf8(""))
        self.param_clock_source.setItemText(1, QtGui.QApplication.translate("AlazarForm", "reference", None, QtGui.QApplication.UnicodeUTF8))
        self.param_clock_source.addItem(_fromUtf8(""))
        self.param_clock_source.setItemText(2, QtGui.QApplication.translate("AlazarForm", "60 MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.param_clock_source.addItem(_fromUtf8(""))
        self.param_clock_source.setItemText(3, QtGui.QApplication.translate("AlazarForm", "1 GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.param_clock_source)
        self.label_5 = QtGui.QLabel(self.ClockSettings)
        self.label_5.setText(QtGui.QApplication.translate("AlazarForm", "Clock Edge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.param_clock_edge = QtGui.QComboBox(self.ClockSettings)
        self.param_clock_edge.setObjectName(_fromUtf8("param_clock_edge"))
        self.param_clock_edge.addItem(_fromUtf8(""))
        self.param_clock_edge.setItemText(0, QtGui.QApplication.translate("AlazarForm", "rising", None, QtGui.QApplication.UnicodeUTF8))
        self.param_clock_edge.addItem(_fromUtf8(""))
        self.param_clock_edge.setItemText(1, QtGui.QApplication.translate("AlazarForm", "falling", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.param_clock_edge)
        self.label_10 = QtGui.QLabel(self.ClockSettings)
        self.label_10.setText(QtGui.QApplication.translate("AlazarForm", "Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.param_timeout = QtGui.QSpinBox(self.ClockSettings)
        self.param_timeout.setMaximum(1000000000)
        self.param_timeout.setProperty("value", 5000)
        self.param_timeout.setObjectName(_fromUtf8("param_timeout"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.param_timeout)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.ClockSettings)
        self.TriggerSettings = QtGui.QGroupBox(self.ScopeSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerSettings.sizePolicy().hasHeightForWidth())
        self.TriggerSettings.setSizePolicy(sizePolicy)
        self.TriggerSettings.setTitle(QtGui.QApplication.translate("AlazarForm", "Trigger Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.TriggerSettings.setObjectName(_fromUtf8("TriggerSettings"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.TriggerSettings)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_7 = QtGui.QLabel(self.TriggerSettings)
        self.label_7.setText(QtGui.QApplication.translate("AlazarForm", "Source 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.param_trigger_source1 = QtGui.QComboBox(self.TriggerSettings)
        self.param_trigger_source1.setObjectName(_fromUtf8("param_trigger_source1"))
        self.param_trigger_source1.addItem(_fromUtf8(""))
        self.param_trigger_source1.setItemText(0, QtGui.QApplication.translate("AlazarForm", "CH_A", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_source1.addItem(_fromUtf8(""))
        self.param_trigger_source1.setItemText(1, QtGui.QApplication.translate("AlazarForm", "CH_B", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_source1.addItem(_fromUtf8(""))
        self.param_trigger_source1.setItemText(2, QtGui.QApplication.translate("AlazarForm", "external", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_source1.addItem(_fromUtf8(""))
        self.param_trigger_source1.setItemText(3, QtGui.QApplication.translate("AlazarForm", "disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.param_trigger_source1)
        self.param_trigger_edge1 = QtGui.QComboBox(self.TriggerSettings)
        self.param_trigger_edge1.setObjectName(_fromUtf8("param_trigger_edge1"))
        self.param_trigger_edge1.addItem(_fromUtf8(""))
        self.param_trigger_edge1.setItemText(0, QtGui.QApplication.translate("AlazarForm", "rising", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_edge1.addItem(_fromUtf8(""))
        self.param_trigger_edge1.setItemText(1, QtGui.QApplication.translate("AlazarForm", "falling", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.param_trigger_edge1)
        self.label_9 = QtGui.QLabel(self.TriggerSettings)
        self.label_9.setText(QtGui.QApplication.translate("AlazarForm", "Level 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.param_trigger_level1 = QtGui.QDoubleSpinBox(self.TriggerSettings)
        self.param_trigger_level1.setProperty("value", 1.0)
        self.param_trigger_level1.setObjectName(_fromUtf8("param_trigger_level1"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.param_trigger_level1)
        self.label_11 = QtGui.QLabel(self.TriggerSettings)
        self.label_11.setText(QtGui.QApplication.translate("AlazarForm", "Coupling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.param_trigger_coupling = QtGui.QComboBox(self.TriggerSettings)
        self.param_trigger_coupling.setObjectName(_fromUtf8("param_trigger_coupling"))
        self.param_trigger_coupling.addItem(_fromUtf8(""))
        self.param_trigger_coupling.setItemText(0, QtGui.QApplication.translate("AlazarForm", "DC", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_coupling.addItem(_fromUtf8(""))
        self.param_trigger_coupling.setItemText(1, QtGui.QApplication.translate("AlazarForm", "AC", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.param_trigger_coupling)
        self.label_8 = QtGui.QLabel(self.TriggerSettings)
        self.label_8.setText(QtGui.QApplication.translate("AlazarForm", "Edge 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_12 = QtGui.QLabel(self.TriggerSettings)
        self.label_12.setText(QtGui.QApplication.translate("AlazarForm", "Source 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.param_trigger_source2 = QtGui.QComboBox(self.TriggerSettings)
        self.param_trigger_source2.setObjectName(_fromUtf8("param_trigger_source2"))
        self.param_trigger_source2.addItem(_fromUtf8(""))
        self.param_trigger_source2.setItemText(0, QtGui.QApplication.translate("AlazarForm", "CH_A", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_source2.addItem(_fromUtf8(""))
        self.param_trigger_source2.setItemText(1, QtGui.QApplication.translate("AlazarForm", "CH_B", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_source2.addItem(_fromUtf8(""))
        self.param_trigger_source2.setItemText(2, QtGui.QApplication.translate("AlazarForm", "external", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_source2.addItem(_fromUtf8(""))
        self.param_trigger_source2.setItemText(3, QtGui.QApplication.translate("AlazarForm", "disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.param_trigger_source2)
        self.param_trigger_edge2 = QtGui.QComboBox(self.TriggerSettings)
        self.param_trigger_edge2.setObjectName(_fromUtf8("param_trigger_edge2"))
        self.param_trigger_edge2.addItem(_fromUtf8(""))
        self.param_trigger_edge2.setItemText(0, QtGui.QApplication.translate("AlazarForm", "rising", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_edge2.addItem(_fromUtf8(""))
        self.param_trigger_edge2.setItemText(1, QtGui.QApplication.translate("AlazarForm", "falling", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.param_trigger_edge2)
        self.label_13 = QtGui.QLabel(self.TriggerSettings)
        self.label_13.setText(QtGui.QApplication.translate("AlazarForm", "Level 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.param_trigger_level2 = QtGui.QDoubleSpinBox(self.TriggerSettings)
        self.param_trigger_level2.setProperty("value", 1.0)
        self.param_trigger_level2.setObjectName(_fromUtf8("param_trigger_level2"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.param_trigger_level2)
        self.label_14 = QtGui.QLabel(self.TriggerSettings)
        self.label_14.setText(QtGui.QApplication.translate("AlazarForm", "Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.TriggerSettings)
        self.label_15.setText(QtGui.QApplication.translate("AlazarForm", "Edge 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.param_trigger_operation = QtGui.QComboBox(self.TriggerSettings)
        self.param_trigger_operation.setObjectName(_fromUtf8("param_trigger_operation"))
        self.param_trigger_operation.addItem(_fromUtf8(""))
        self.param_trigger_operation.setItemText(0, QtGui.QApplication.translate("AlazarForm", "or", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_operation.addItem(_fromUtf8(""))
        self.param_trigger_operation.setItemText(1, QtGui.QApplication.translate("AlazarForm", "and", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_operation.addItem(_fromUtf8(""))
        self.param_trigger_operation.setItemText(2, QtGui.QApplication.translate("AlazarForm", "xor", None, QtGui.QApplication.UnicodeUTF8))
        self.param_trigger_operation.addItem(_fromUtf8(""))
        self.param_trigger_operation.setItemText(3, QtGui.QApplication.translate("AlazarForm", "and not", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.param_trigger_operation)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.TriggerSettings)
        self.applyButton = QtGui.QPushButton(self.ScopeSettings)
        self.applyButton.setText(QtGui.QApplication.translate("AlazarForm", "Apply Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.verticalLayout_5.addWidget(self.applyButton)

        self.retranslateUi(AlazarForm)
        self.param_trigger_source1.setCurrentIndex(2)
        self.param_trigger_source2.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(AlazarForm)

    def retranslateUi(self, AlazarForm):
        pass

