# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TSweep.ui'
#
# Created: Mon Dec 26 21:23:11 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TSweepWindow(object):
    def setupUi(self, TSweepWindow):
        TSweepWindow.setObjectName(_fromUtf8("TSweepWindow"))
        TSweepWindow.resize(944, 675)
        self.centralwidget = QtGui.QWidget(TSweepWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.powerSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.powerSpinBox.setMinimum(-100.0)
        self.powerSpinBox.setMaximum(10.0)
        self.powerSpinBox.setProperty(_fromUtf8("value"), -20.0)
        self.powerSpinBox.setObjectName(_fromUtf8("powerSpinBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.powerSpinBox)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.sweep_ptsSpinBox = QtGui.QSpinBox(self.groupBox)
        self.sweep_ptsSpinBox.setMaximum(1601)
        self.sweep_ptsSpinBox.setProperty(_fromUtf8("value"), 1601)
        self.sweep_ptsSpinBox.setObjectName(_fromUtf8("sweep_ptsSpinBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sweep_ptsSpinBox)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.ifbwSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.ifbwSpinBox.setMinimum(10.0)
        self.ifbwSpinBox.setMaximum(1000000.0)
        self.ifbwSpinBox.setProperty(_fromUtf8("value"), 1000.0)
        self.ifbwSpinBox.setObjectName(_fromUtf8("ifbwSpinBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ifbwSpinBox)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.avgsSpinBox = QtGui.QSpinBox(self.groupBox)
        self.avgsSpinBox.setMinimum(1)
        self.avgsSpinBox.setObjectName(_fromUtf8("avgsSpinBox"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.avgsSpinBox)
        self.centerstartLabel = QtGui.QLabel(self.groupBox)
        self.centerstartLabel.setObjectName(_fromUtf8("centerstartLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.centerstartLabel)
        self.centerstartSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.centerstartSpinBox.setDecimals(6)
        self.centerstartSpinBox.setMaximum(20.0)
        self.centerstartSpinBox.setSingleStep(0.1)
        self.centerstartSpinBox.setProperty(_fromUtf8("value"), 10.0)
        self.centerstartSpinBox.setObjectName(_fromUtf8("centerstartSpinBox"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.centerstartSpinBox)
        self.spanstopLabel = QtGui.QLabel(self.groupBox)
        self.spanstopLabel.setObjectName(_fromUtf8("spanstopLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.spanstopLabel)
        self.spanstopSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spanstopSpinBox.sizePolicy().hasHeightForWidth())
        self.spanstopSpinBox.setSizePolicy(sizePolicy)
        self.spanstopSpinBox.setMaximum(20000.0)
        self.spanstopSpinBox.setProperty(_fromUtf8("value"), 1000.0)
        self.spanstopSpinBox.setObjectName(_fromUtf8("spanstopSpinBox"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.spanstopSpinBox)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.centerspanstartstopCheckBox = QtGui.QCheckBox(self.groupBox)
        self.centerspanstartstopCheckBox.setChecked(True)
        self.centerspanstartstopCheckBox.setObjectName(_fromUtf8("centerspanstartstopCheckBox"))
        self.verticalLayout_3.addWidget(self.centerspanstartstopCheckBox)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_7.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout_7.addWidget(self.radioButton_2)
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.maxTSpinBox = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.maxTSpinBox.setObjectName(_fromUtf8("maxTSpinBox"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.maxTSpinBox)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.delaySpinBox = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.delaySpinBox.setObjectName(_fromUtf8("delaySpinBox"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.delaySpinBox)
        self.analysisCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.analysisCheckBox.setObjectName(_fromUtf8("analysisCheckBox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.analysisCheckBox)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.temperatureLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.temperatureLabel.setFont(font)
        self.temperatureLabel.setObjectName(_fromUtf8("temperatureLabel"))
        self.verticalLayout_7.addWidget(self.temperatureLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.go_button = QtGui.QPushButton(self.centralwidget)
        self.go_button.setObjectName(_fromUtf8("go_button"))
        self.horizontalLayout_2.addWidget(self.go_button)
        self.abort_button = QtGui.QPushButton(self.centralwidget)
        self.abort_button.setObjectName(_fromUtf8("abort_button"))
        self.horizontalLayout_2.addWidget(self.abort_button)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.dataCurveWidget = CurveWidget(self.groupBox_2)
        self.dataCurveWidget.setOrientation(QtCore.Qt.Horizontal)
        self.dataCurveWidget.setObjectName(_fromUtf8("dataCurveWidget"))
        self.verticalLayout_5.addWidget(self.dataCurveWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.traceNumSpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.traceNumSpinBox.setObjectName(_fromUtf8("traceNumSpinBox"))
        self.horizontalLayout_5.addWidget(self.traceNumSpinBox)
        self.browserTLabel = QtGui.QLabel(self.groupBox_2)
        self.browserTLabel.setObjectName(_fromUtf8("browserTLabel"))
        self.horizontalLayout_5.addWidget(self.browserTLabel)
        self.autoCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.autoCheckBox.setChecked(True)
        self.autoCheckBox.setObjectName(_fromUtf8("autoCheckBox"))
        self.horizontalLayout_5.addWidget(self.autoCheckBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.f0CurveWidget = CurveWidget(self.groupBox_3)
        self.f0CurveWidget.setOrientation(QtCore.Qt.Horizontal)
        self.f0CurveWidget.setObjectName(_fromUtf8("f0CurveWidget"))
        self.verticalLayout_6.addWidget(self.f0CurveWidget)
        self.QCurveWidget = CurveWidget(self.groupBox_3)
        self.QCurveWidget.setOrientation(QtCore.Qt.Horizontal)
        self.QCurveWidget.setObjectName(_fromUtf8("QCurveWidget"))
        self.verticalLayout_6.addWidget(self.QCurveWidget)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.exptpathButton = QtGui.QPushButton(self.centralwidget)
        self.exptpathButton.setObjectName(_fromUtf8("exptpathButton"))
        self.horizontalLayout_3.addWidget(self.exptpathButton)
        self.exptpathLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.exptpathLineEdit.setObjectName(_fromUtf8("exptpathLineEdit"))
        self.horizontalLayout_3.addWidget(self.exptpathLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.filenumberLabel = QtGui.QLabel(self.centralwidget)
        self.filenumberLabel.setObjectName(_fromUtf8("filenumberLabel"))
        self.horizontalLayout_6.addWidget(self.filenumberLabel)
        self.prefixLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.prefixLineEdit.setObjectName(_fromUtf8("prefixLineEdit"))
        self.horizontalLayout_6.addWidget(self.prefixLineEdit)
        self.saveCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.saveCheckBox.setObjectName(_fromUtf8("saveCheckBox"))
        self.horizontalLayout_6.addWidget(self.saveCheckBox)
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_6.addWidget(self.checkBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.message_box = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_box.sizePolicy().hasHeightForWidth())
        self.message_box.setSizePolicy(sizePolicy)
        self.message_box.setMaximumSize(QtCore.QSize(16777215, 80))
        self.message_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.message_box.setObjectName(_fromUtf8("message_box"))
        self.verticalLayout_2.addWidget(self.message_box)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.cmd_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.cmd_lineEdit.setObjectName(_fromUtf8("cmd_lineEdit"))
        self.verticalLayout_4.addWidget(self.cmd_lineEdit)
        TSweepWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(TSweepWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 944, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave = QtGui.QMenu(self.menuFile)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuInstruments = QtGui.QMenu(self.menubar)
        self.menuInstruments.setObjectName(_fromUtf8("menuInstruments"))
        TSweepWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(TSweepWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        TSweepWindow.setStatusBar(self.statusbar)
        self.actionExperimental_Settings = QtGui.QAction(TSweepWindow)
        self.actionExperimental_Settings.setObjectName(_fromUtf8("actionExperimental_Settings"))
        self.actionExperimental_and_Instrument_Settings = QtGui.QAction(TSweepWindow)
        self.actionExperimental_and_Instrument_Settings.setObjectName(_fromUtf8("actionExperimental_and_Instrument_Settings"))
        self.actionLoad = QtGui.QAction(TSweepWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.menuSave.addAction(self.actionExperimental_Settings)
        self.menuSave.addAction(self.actionExperimental_and_Instrument_Settings)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.actionLoad)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInstruments.menuAction())

        self.retranslateUi(TSweepWindow)
        QtCore.QMetaObject.connectSlotsByName(TSweepWindow)

    def retranslateUi(self, TSweepWindow):
        TSweepWindow.setWindowTitle(QtGui.QApplication.translate("TSweepWindow", "Temperature Sweep with Network Analyzer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("TSweepWindow", "NWA Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TSweepWindow", "Power", None, QtGui.QApplication.UnicodeUTF8))
        self.powerSpinBox.setSuffix(QtGui.QApplication.translate("TSweepWindow", " dBm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TSweepWindow", "Sweep pts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TSweepWindow", "IF BW", None, QtGui.QApplication.UnicodeUTF8))
        self.ifbwSpinBox.setSuffix(QtGui.QApplication.translate("TSweepWindow", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TSweepWindow", "Avgs", None, QtGui.QApplication.UnicodeUTF8))
        self.centerstartLabel.setText(QtGui.QApplication.translate("TSweepWindow", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.centerstartSpinBox.setSuffix(QtGui.QApplication.translate("TSweepWindow", " GHz", None, QtGui.QApplication.UnicodeUTF8))
        self.spanstopLabel.setText(QtGui.QApplication.translate("TSweepWindow", "Span", None, QtGui.QApplication.UnicodeUTF8))
        self.spanstopSpinBox.setSuffix(QtGui.QApplication.translate("TSweepWindow", " MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.centerspanstartstopCheckBox.setText(QtGui.QApplication.translate("TSweepWindow", "Start/Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("TSweepWindow", "T Sweep Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("TSweepWindow", "Fit type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("TSweepWindow", "Series", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("TSweepWindow", "Hanger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TSweepWindow", "Max T", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("TSweepWindow", "Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.analysisCheckBox.setText(QtGui.QApplication.translate("TSweepWindow", "Analysis Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.temperatureLabel.setText(QtGui.QApplication.translate("TSweepWindow", "Current T: N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.go_button.setText(QtGui.QApplication.translate("TSweepWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.abort_button.setText(QtGui.QApplication.translate("TSweepWindow", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("TSweepWindow", "Curve Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TSweepWindow", "Trace number", None, QtGui.QApplication.UnicodeUTF8))
        self.browserTLabel.setText(QtGui.QApplication.translate("TSweepWindow", "T= N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.autoCheckBox.setText(QtGui.QApplication.translate("TSweepWindow", "auto", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("TSweepWindow", "Analyzed Data", None, QtGui.QApplication.UnicodeUTF8))
        self.exptpathButton.setText(QtGui.QApplication.translate("TSweepWindow", "Experiment Path", None, QtGui.QApplication.UnicodeUTF8))
        self.exptpathLineEdit.setText(QtGui.QApplication.translate("TSweepWindow", "S:\\_Data\\", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("TSweepWindow", "File Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.filenumberLabel.setText(QtGui.QApplication.translate("TSweepWindow", "000_", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixLineEdit.setText(QtGui.QApplication.translate("TSweepWindow", "TSweep", None, QtGui.QApplication.UnicodeUTF8))
        self.saveCheckBox.setText(QtGui.QApplication.translate("TSweepWindow", "Save Traces", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("TSweepWindow", "Save Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.message_box.setHtml(QtGui.QApplication.translate("TSweepWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("TSweepWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("TSweepWindow", "Save..", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInstruments.setTitle(QtGui.QApplication.translate("TSweepWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExperimental_Settings.setText(QtGui.QApplication.translate("TSweepWindow", "Experimental Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExperimental_and_Instrument_Settings.setText(QtGui.QApplication.translate("TSweepWindow", "Experimental and Instrument Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("TSweepWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))

from guiqwt.plot import CurveWidget
