HviAttribute_AwgInstruction = 1000000
SD_AOU_Hvi_Instructions_SetAmplitude_Id = (HviAttribute_AwgInstruction + 10000 * 1)
SD_AOU_Hvi_Instructions_SetAmplitude_Parameters_Channel_Id = (SD_AOU_Hvi_Instructions_SetAmplitude_Id + 100 * 1)
SD_AOU_Hvi_Instructions_SetAmplitude_Parameters_ApplyDelayed_Id = (SD_AOU_Hvi_Instructions_SetAmplitude_Id + 100 * 2)
SD_AOU_Hvi_Instructions_SetAmplitude_Parameters_Value_Id = (SD_AOU_Hvi_Instructions_SetAmplitude_Id + 100 * 3)
SD_AOU_Hvi_Instructions_SetWaveshape_Id = (HviAttribute_AwgInstruction + 10000 * 2)
SD_AOU_Hvi_Instructions_SetWaveshape_Parameters_Channel_Id = (SD_AOU_Hvi_Instructions_SetWaveshape_Id + 100 * 1)
SD_AOU_Hvi_Instructions_SetWaveshape_Parameters_ApplyDelayed_Id = (SD_AOU_Hvi_Instructions_SetWaveshape_Id + 100 * 2)
SD_AOU_Hvi_Instructions_SetWaveshape_Parameters_Value_Id = (SD_AOU_Hvi_Instructions_SetWaveshape_Id + 100 * 3)
SD_AOU_Hvi_Instructions_SetOffset_Id = (HviAttribute_AwgInstruction + 10000 * 3)
SD_AOU_Hvi_Instructions_SetOffset_Parameters_Channel_Id = (SD_AOU_Hvi_Instructions_SetOffset_Id + 100 * 1)
SD_AOU_Hvi_Instructions_SetOffset_Parameters_ApplyDelayed_Id = (SD_AOU_Hvi_Instructions_SetOffset_Id + 100 * 2)
SD_AOU_Hvi_Instructions_SetOffset_Parameters_Value_Id = (SD_AOU_Hvi_Instructions_SetOffset_Id + 100 * 3)
SD_AOU_Hvi_Instructions_SetFrequency_Id = (HviAttribute_AwgInstruction + 10000 * 4)
SD_AOU_Hvi_Instructions_SetFrequency_Parameters_Channel_Id = (SD_AOU_Hvi_Instructions_SetFrequency_Id + 100 * 1)
SD_AOU_Hvi_Instructions_SetFrequency_Parameters_ApplyDelayed_Id = (SD_AOU_Hvi_Instructions_SetFrequency_Id + 100 * 2)
SD_AOU_Hvi_Instructions_SetFrequency_Parameters_Value_Id = (SD_AOU_Hvi_Instructions_SetFrequency_Id + 100 * 3)
SD_AOU_Hvi_Instructions_SetPhase_Id = (HviAttribute_AwgInstruction + 10000 * 5)
SD_AOU_Hvi_Instructions_SetPhase_Parameters_Channel_Id = (SD_AOU_Hvi_Instructions_SetPhase_Id + 100 * 1)
SD_AOU_Hvi_Instructions_SetPhase_Parameters_ApplyDelayed_Id = (SD_AOU_Hvi_Instructions_SetPhase_Id + 100 * 2)
SD_AOU_Hvi_Instructions_SetPhase_Parameters_Value_Id = (SD_AOU_Hvi_Instructions_SetPhase_Id + 100 * 3)
SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Id = (HviAttribute_AwgInstruction + 10000 * 6)
SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Parameters_Channel_Id = (SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Id + 100 * 1)
SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Parameters_ApplyDelayed_Id = (SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Id + 100 * 2)
SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Parameters_ModType_Id = (SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Id + 100 * 3)
SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Parameters_ModSource_Id = (SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Id + 100 * 4)
SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Parameters_DevGain_Id = (SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Id + 100 * 5)
SD_AOU_Hvi_Instructions_ModulationAmpOffsetConfig_Id = (HviAttribute_AwgInstruction + 10000 * 7)
SD_AOU_Hvi_Instructions_ModulationAmpOffsetConfig_Parameters_Channel_Id = (SD_AOU_Hvi_Instructions_ModulationAmpOffsetConfig_Id + 100 * 1)
SD_AOU_Hvi_Instructions_ModulationAmpOffsetConfig_Parameters_ApplyDelayed_Id = (SD_AOU_Hvi_Instructions_ModulationAmpOffsetConfig_Id + 100 * 2)
SD_AOU_Hvi_Instructions_ModulationAmpOffsetConfig_Parameters_ModType_Id = (SD_AOU_Hvi_Instructions_ModulationAmpOffsetConfig_Id + 100 * 3)
SD_AOU_Hvi_Instructions_ModulationAmpOffsetConfig_Parameters_ModSource_Id = (SD_AOU_Hvi_Instructions_ModulationAmpOffsetConfig_Id + 100 * 4)
SD_AOU_Hvi_Instructions_ModulationAmpOffsetConfig_Parameters_Gain_Id = (SD_AOU_Hvi_Instructions_ModulationAmpOffsetConfig_Id + 100 * 5)
SD_AOU_Hvi_Instructions_ModulationIQConfig_Id = (HviAttribute_AwgInstruction + 10000 * 8)
SD_AOU_Hvi_Instructions_ModulationIQConfig_Parameters_Channel_Id = (SD_AOU_Hvi_Instructions_ModulationIQConfig_Id + 100 * 1)
SD_AOU_Hvi_Instructions_ModulationIQConfig_Parameters_ApplyDelayed_Id = (SD_AOU_Hvi_Instructions_ModulationIQConfig_Id + 100 * 2)
SD_AOU_Hvi_Instructions_ModulationIQConfig_Parameters_Enable_Id = (SD_AOU_Hvi_Instructions_ModulationIQConfig_Id + 100 * 3)
SD_AOU_Hvi_Instructions_ModulationIQConfig_Parameters_TypeAmpOffset_Id = (SD_AOU_Hvi_Instructions_ModulationIQConfig_Id + 100 * 4)
SD_AOU_Hvi_Instructions_ModulationIQConfig_Parameters_GainAmpOffset_Id = (SD_AOU_Hvi_Instructions_ModulationIQConfig_Id + 100 * 5)
SD_AOU_Hvi_Instructions_ModulationIQConfig_Parameters_TypeFreqPhase_Id = (SD_AOU_Hvi_Instructions_ModulationIQConfig_Id + 100 * 6)
SD_AOU_Hvi_Instructions_ModulationIQConfig_Parameters_GainFreqPhase_Id = (SD_AOU_Hvi_Instructions_ModulationIQConfig_Id + 100 * 7)
HviAttribute_AwgParameterValue = 5000000
HviAttribute_AwgWaveshape = (HviAttribute_AwgParameterValue + 100 * 0)
SD_AOU_Hvi_Instructions_SetWaveshape_Parameters_Value_AOU_HIZ_Id = (HviAttribute_AwgWaveshape + 0)
SD_AOU_Hvi_Instructions_SetWaveshape_Parameters_Value_AOU_OFF_Id = (HviAttribute_AwgWaveshape + 1)
SD_AOU_Hvi_Instructions_SetWaveshape_Parameters_Value_AOU_SINUSOIDAL_Id = (HviAttribute_AwgWaveshape + 2)
SD_AOU_Hvi_Instructions_SetWaveshape_Parameters_Value_AOU_TRIANGULAR_Id = (HviAttribute_AwgWaveshape + 3)
SD_AOU_Hvi_Instructions_SetWaveshape_Parameters_Value_AOU_SQUARE_Id = (HviAttribute_AwgWaveshape + 4)
SD_AOU_Hvi_Instructions_SetWaveshape_Parameters_Value_AOU_DC_Id = (HviAttribute_AwgWaveshape + 5)
SD_AOU_Hvi_Instructions_SetWaveshape_Parameters_Value_AOU_AWG_Id = (HviAttribute_AwgWaveshape + 6)
SD_AOU_Hvi_Instructions_SetWaveshape_Parameters_Value_AOU_PARTNER_Id = (HviAttribute_AwgWaveshape + 7)
HviAttribute_AwgModulationType = (HviAttribute_AwgParameterValue + 100 * 1)
SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Parameters_ModType_AOU_MOD_OFF_Id = (HviAttribute_AwgModulationType + 1)
SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Parameters_ModType_AOU_MOD_FM_Id = (HviAttribute_AwgModulationType + 2)
SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Parameters_ModType_AOU_MOD_PHASE_Id = (HviAttribute_AwgModulationType + 3)
SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Parameters_ModType_AOU_MOD_AM_Id = (HviAttribute_AwgModulationType + 4)
SD_AOU_Hvi_Instructions_ModulationFreqPhaseConfig_Parameters_ModType_AOU_MOD_OFFSET_Id = (HviAttribute_AwgModulationType + 5)
SD_AOU_Hvi_Instructions_QueueWaveform_Id = (HviAttribute_AwgInstruction + 10000 * 10)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_Channel_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Id + 100 * 1)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_ApplyDelayed_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Id + 100 * 2)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_WaveformId_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Id + 100 * 3)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Id + 100 * 4)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_Cycles_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Id + 100 * 5)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_StartDelay_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Id + 100 * 6)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_Prescaler_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Id + 100 * 7)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_AUTOTRIG_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_Id + 1)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_VIHVITRIG_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_Id + 2)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_SWHVITRIG_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_Id + 3)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_EXTTRIG_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_Id + 4)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_ANALOGTRIG_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_Id + 5)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_SWHVITRIG_CYCLE_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_Id + 6)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_EXTTRIG_CYCLE_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_Id + 7)
SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_ANALOGAUTOTRIG_Id = (SD_AOU_Hvi_Instructions_QueueWaveform_Parameters_TriggerMode_Id + 8)
HviAttribute_DigitizerInstruction = 2000000
SD_AIN_Hvi_Instructions_DaqConfigInstruction_Id = (HviAttribute_DigitizerInstruction + 10000 * 1)
SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_Channel_Id = (SD_AIN_Hvi_Instructions_DaqConfigInstruction_Id + 100 * 1)
SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_ApplyDelayed_Id = (SD_AIN_Hvi_Instructions_DaqConfigInstruction_Id + 100 * 2)
SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_Cycles_Id = (SD_AIN_Hvi_Instructions_DaqConfigInstruction_Id + 100 * 3)
SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_PointsPerCycle_Id = (SD_AIN_Hvi_Instructions_DaqConfigInstruction_Id + 100 * 4)
SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_TriggerMode_Id = (SD_AIN_Hvi_Instructions_DaqConfigInstruction_Id + 100 * 5)
SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_TriggerDelay_Id = (SD_AIN_Hvi_Instructions_DaqConfigInstruction_Id + 100 * 6)
SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_TriggerMode_AUTOTRIG_Id = (SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_TriggerMode_Id + 1)
SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_TriggerMode_SWHVITRIG1_Id = (SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_TriggerMode_Id + 2)
SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_TriggerMode_HWDIGTRIG_Id = (SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_TriggerMode_Id + 3)
SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_TriggerMode_HWANATRIG_Id = (SD_AIN_Hvi_Instructions_DaqConfigInstruction_Parameters_TriggerMode_Id + 4)
SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Id = (HviAttribute_DigitizerInstruction + 10000 * 2)
SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Parameters_Channel_Id = (SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Id + 100 * 1)
SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Parameters_ApplyDelayed_Id = (SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Id + 100 * 2)
SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Parameters_AnalogTriggerMode_Id = (SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Id + 100 * 3)
SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Parameters_Threshold_Id = (SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Id + 100 * 4)
SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Parameters_AnalogTriggerMode_AIN_RISING_EDGE_Id = (SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Parameters_AnalogTriggerMode_Id + 1)
SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Parameters_AnalogTriggerMode_AIN_FALLING_EDGE_Id = (SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Parameters_AnalogTriggerMode_Id + 2)
SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Parameters_AnalogTriggerMode_AIN_BOTH_EDGES_Id = (SD_AIN_Hvi_Instructions_ChannelTriggerConfigInstruction_Parameters_AnalogTriggerMode_Id + 3)
SD_AIN_Hvi_Instructions_DaqAnalogTriggerConfigInstruction_Id = (HviAttribute_DigitizerInstruction + 10000 * 3)
SD_AIN_Hvi_Instructions_DaqAnalogTriggerConfigInstruction_Parameters_Channel_Id = (SD_AIN_Hvi_Instructions_DaqAnalogTriggerConfigInstruction_Id + 100 * 1)
SD_AIN_Hvi_Instructions_DaqAnalogTriggerConfigInstruction_Parameters_ApplyDelayed_Id = (SD_AIN_Hvi_Instructions_DaqAnalogTriggerConfigInstruction_Id + 100 * 2)
SD_AIN_Hvi_Instructions_DaqAnalogTriggerConfigInstruction_Parameters_AnalogTriggerMask_Id = (SD_AIN_Hvi_Instructions_DaqAnalogTriggerConfigInstruction_Id + 100 * 3)
SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Id = (HviAttribute_DigitizerInstruction + 10000 * 4)
SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_Channel_Id = (SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Id + 100 * 1)
SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_ApplyDelayed_Id = (SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Id + 100 * 2)
SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_TriggerMode_Id = (SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Id + 100 * 3)
SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_TriggerSource_Id = (SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Id + 100 * 4)
SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_TriggerMode_TRIGGER_HIGH_Id = (SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_TriggerMode_Id + 1)
SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_TriggerMode_TRIGGER_LOW_Id = (SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_TriggerMode_Id + 2)
SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_TriggerMode_TRIGGER_RISE_Id = (SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_TriggerMode_Id + 3)
SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_TriggerMode_TRIGGER_FALL_Id = (SD_AIN_Hvi_Instructions_DaqDigitalTriggerConfigInstruction_Parameters_TriggerMode_Id + 4)
SD_AIN_Hvi_Instructions_ChannelPrescalerConfigInstruction_Id = (HviAttribute_DigitizerInstruction + 10000 * 5)
SD_AIN_Hvi_Instructions_ChannelPrescalerConfigInstruction_Parameters_Channel_Id = (SD_AIN_Hvi_Instructions_ChannelPrescalerConfigInstruction_Id + 100 * 1)
SD_AIN_Hvi_Instructions_ChannelPrescalerConfigInstruction_Parameters_ApplyDelayed_Id = (SD_AIN_Hvi_Instructions_ChannelPrescalerConfigInstruction_Id + 100 * 2)
SD_AIN_Hvi_Instructions_ChannelPrescalerConfigInstruction_Parameters_Prescaler_Id = (SD_AIN_Hvi_Instructions_ChannelPrescalerConfigInstruction_Id + 100 * 3)
SD_AIN_Action_DAQ1Start = 0
SD_AIN_Action_DAQ2Start = 1
SD_AIN_Action_DAQ3Start = 2
SD_AIN_Action_DAQ4Start = 3
SD_AIN_Action_DAQ1Stop = 4
SD_AIN_Action_DAQ2Stop = 5
SD_AIN_Action_DAQ3Stop = 6
SD_AIN_Action_DAQ4Stop = 7
SD_AIN_Action_DAQ1Resume = 8
SD_AIN_Action_DAQ2Resume = 9
SD_AIN_Action_DAQ3Resume = 10
SD_AIN_Action_DAQ4Resume = 11
SD_AIN_Action_DAQ1Trigger = 12
SD_AIN_Action_DAQ2Trigger = 13
SD_AIN_Action_DAQ3Trigger = 14
SD_AIN_Action_DAQ4Trigger = 15
SD_AIN_Action_DAQ1Flush = 16
SD_AIN_Action_DAQ2Flush = 17
SD_AIN_Action_DAQ3Flush = 18
SD_AIN_Action_DAQ4Flush = 19
SD_AIN_Action_UserFpga0 = 20
SD_AIN_Action_UserFpga1 = 21
SD_AIN_Action_UserFpga2 = 22
SD_AIN_Action_UserFpga3 = 23
SD_AIN_Action_UserFpga4 = 24
SD_AIN_Action_UserFpga5 = 25
SD_AIN_Action_UserFpga6 = 26
SD_AIN_Action_UserFpga7 = 27
SD_AIN_Action_ApplyInstructions = 28
SD_AIN_Event_DAQ1Empty = 0
SD_AIN_Event_DAQ2Empty = 1
SD_AIN_Event_DAQ3Empty = 2
SD_AIN_Event_DAQ4Empty = 3
SD_AIN_Event_DAQ1Running = 4
SD_AIN_Event_DAQ2Running = 5
SD_AIN_Event_DAQ3Running = 6
SD_AIN_Event_DAQ4Running = 7
SD_AIN_Event_DAQ1TriggerLoopback = 8
SD_AIN_Event_DAQ2TriggerLoopback = 9
SD_AIN_Event_DAQ3TriggerLoopback = 10
SD_AIN_Event_DAQ4TriggerLoopback = 11
SD_AIN_Event_FpgaUser0 = 12
SD_AIN_Event_UserFpgaLoopback1 = 13
SD_AIN_Event_UserFpgaLoopback2 = 14
SD_AIN_Event_UserFpgaLoopback3 = 15
SD_AIN_Event_UserFpgaLoopback4 = 16
SD_AIN_Event_UserFpgaLoopback5 = 17
SD_AIN_Event_UserFpgaLoopback6 = 18
SD_AIN_Event_UserFpgaLoopback7 = 19
SD_AIN_Event_SandBoxPxiTrigger0 = 20
SD_AIN_Event_SandBoxPxiTrigger1 = 21
SD_AIN_Event_SandBoxPxiTrigger2 = 22
SD_AIN_Event_SandBoxPxiTrigger3 = 23
SD_AIN_Event_SandBoxPxiTrigger4 = 24
SD_AIN_Event_SandBoxPxiTrigger5 = 25
SD_AIN_Event_SandBoxPxiTrigger6 = 26
SD_AIN_Event_SandBoxPxiTrigger7 = 27
SD_AIN_Event_SandBoxFrontPanelTrigger0 = 28
SD_AOU_Action_CH1ResetPhase = 0
SD_AOU_Action_CH2ResetPhase = 1
SD_AOU_Action_CH3ResetPhase = 2
SD_AOU_Action_CH4ResetPhase = 3
SD_AOU_Action_AWG1Start = 4
SD_AOU_Action_AWG2Start = 5
SD_AOU_Action_AWG3Start = 6
SD_AOU_Action_AWG4Start = 7
SD_AOU_Action_AWG1Stop = 8
SD_AOU_Action_AWG2Stop = 9
SD_AOU_Action_AWG3Stop = 10
SD_AOU_Action_AWG4Stop = 11
SD_AOU_Action_AWG1Pause = 12
SD_AOU_Action_AWG2Pause = 13
SD_AOU_Action_AWG3Pause = 14
SD_AOU_Action_AWG4Pause = 15
SD_AOU_Action_AWG1Resume = 16
SD_AOU_Action_AWG2Resume = 17
SD_AOU_Action_AWG3Resume = 18
SD_AOU_Action_AWG4Resume = 19
SD_AOU_Action_AWG1Trigger = 20
SD_AOU_Action_AWG2Trigger = 21
SD_AOU_Action_AWG3Trigger = 22
SD_AOU_Action_AWG4Trigger = 23
SD_AOU_Action_AWG1JumpNextWaveform = 24
SD_AOU_Action_AWG2JumpNextWaveform = 25
SD_AOU_Action_AWG3JumpNextWaveform = 26
SD_AOU_Action_AWG4JumpNextWaveform = 27
SD_AOU_Action_AWG1QueueFlush = 28
SD_AOU_Action_AWG2QueueFlush = 29
SD_AOU_Action_AWG3QueueFlush = 30
SD_AOU_Action_AWG4QueueFlush = 31
SD_AOU_Action_UserFpga0 = 32
SD_AOU_Action_UserFpga1 = 33
SD_AOU_Action_UserFpga2 = 34
SD_AOU_Action_UserFpga3 = 35
SD_AOU_Action_UserFpga4 = 36
SD_AOU_Action_UserFpga5 = 37
SD_AOU_Action_UserFpga6 = 38
SD_AOU_Action_UserFpga7 = 39
SD_AOU_Action_ApplyInstructions = 40
SD_AOU_Event_AWG1QueueEmpty = 0
SD_AOU_Event_AWG2QueueEmpty = 1
SD_AOU_Event_AWG3QueueEmpty = 2
SD_AOU_Event_AWG4QueueEmpty = 3
SD_AOU_Event_AWG1QueueFull = 4
SD_AOU_Event_AWG2QueueFull = 5
SD_AOU_Event_AWG3QueueFull = 6
SD_AOU_Event_AWG4QueueFull = 7
SD_AOU_Event_AWG1Underrun = 8
SD_AOU_Event_AWG2Underrun = 9
SD_AOU_Event_AWG3Underrun = 10
SD_AOU_Event_AWG4Underrun = 11
SD_AOU_Event_AWG1QueueEnd = 12
SD_AOU_Event_AWG2QueueEnd = 13
SD_AOU_Event_AWG3QueueEnd = 14
SD_AOU_Event_AWG4QueueEnd = 15
SD_AOU_Event_AWG1WfStart = 16
SD_AOU_Event_AWG2WfStart = 17
SD_AOU_Event_AWG3WfStart = 18
SD_AOU_Event_AWG4WfStart = 19
SD_AOU_Event_AWG1QueueMarker = 20
SD_AOU_Event_AWG2QueueMarker = 21
SD_AOU_Event_AWG3QueueMarker = 22
SD_AOU_Event_AWG4QueueMarker = 23
SD_AOU_Event_AWG1QueueFlushed = 24
SD_AOU_Event_AWG2QueueFlushed = 25
SD_AOU_Event_AWG3QueueFlushed = 26
SD_AOU_Event_AWG4QueueFlushed = 27
SD_AOU_Event_AWG1QueueRunning = 28
SD_AOU_Event_AWG2QueueRunning = 29
SD_AOU_Event_AWG3QueueRunning = 30
SD_AOU_Event_AWG4QueueRunning = 31
SD_AOU_Event_UserFpgaLoopback0 = 32
SD_AOU_Event_UserFpgaLoopback1 = 33
SD_AOU_Event_UserFpgaLoopback2 = 34
SD_AOU_Event_UserFpgaLoopback3 = 35
SD_AOU_Event_UserFpgaLoopback4 = 36
SD_AOU_Event_UserFpgaLoopback5 = 37
SD_AOU_Event_UserFpgaLoopback6 = 38
SD_AOU_Event_UserFpgaLoopback7 = 39
SD_AOU_Event_SandBoxPxiTrigger0 = 40
SD_AOU_Event_SandBoxPxiTrigger1 = 41
SD_AOU_Event_SandBoxPxiTrigger2 = 42
SD_AOU_Event_SandBoxPxiTrigger3 = 43
SD_AOU_Event_SandBoxPxiTrigger4 = 44
SD_AOU_Event_SandBoxPxiTrigger5 = 45
SD_AOU_Event_SandBoxPxiTrigger6 = 46
SD_AOU_Event_SandBoxPxiTrigger7 = 47
SD_AOU_Event_SandBoxFrontPanelTrigger0 = 48
SD_AOU_Event_AWG1TriggerLoopback = 49
SD_AOU_Event_AWG2TriggerLoopback = 50
SD_AOU_Event_AWG3TriggerLoopback = 51
SD_AOU_Event_AWG4TriggerLoopback = 52
SD_AIO_Action_CH1ResetPhase = 0
SD_AIO_Action_CH2ResetPhase = 1
SD_AIO_Action_CH3ResetPhase = 2
SD_AIO_Action_CH4ResetPhase = 3
SD_AIO_Action_AWG1Start = 4
SD_AIO_Action_AWG2Start = 5
SD_AIO_Action_AWG3Start = 6
SD_AIO_Action_AWG4Start = 7
SD_AIO_Action_AWG1Stop = 8
SD_AIO_Action_AWG2Stop = 9
SD_AIO_Action_AWG3Stop = 10
SD_AIO_Action_AWG4Stop = 11
SD_AIO_Action_AWG1Pause = 12
SD_AIO_Action_AWG2Pause = 13
SD_AIO_Action_AWG3Pause = 14
SD_AIO_Action_AWG4Pause = 15
SD_AIO_Action_AWG1Resume = 16
SD_AIO_Action_AWG2Resume = 17
SD_AIO_Action_AWG3Resume = 18
SD_AIO_Action_AWG4Resume = 19
SD_AIO_Action_AWG1Trigger = 20
SD_AIO_Action_AWG2Trigger = 21
SD_AIO_Action_AWG3Trigger = 22
SD_AIO_Action_AWG4Trigger = 23
SD_AIO_Action_AWG1JumpNextWaveform = 24
SD_AIO_Action_AWG2JumpNextWaveform = 25
SD_AIO_Action_AWG3JumpNextWaveform = 26
SD_AIO_Action_AWG4JumpNextWaveform = 27
SD_AIO_Action_AWG1QueueFlush = 28
SD_AIO_Action_AWG2QueueFlush = 29
SD_AIO_Action_AWG3QueueFlush = 30
SD_AIO_Action_AWG4QueueFlush = 31
SD_AIO_Action_DAQ1Start = 32
SD_AIO_Action_DAQ2Start = 33
SD_AIO_Action_DAQ3Start = 34
SD_AIO_Action_DAQ4Start = 35
SD_AIO_Action_DAQ5Start = 36
SD_AIO_Action_DAQ6Start = 37
SD_AIO_Action_DAQ7Start = 38
SD_AIO_Action_DAQ8Start = 39
SD_AIO_Action_DAQ1Stop = 40
SD_AIO_Action_DAQ2Stop = 41
SD_AIO_Action_DAQ3Stop = 42
SD_AIO_Action_DAQ4Stop = 43
SD_AIO_Action_DAQ5Stop = 44
SD_AIO_Action_DAQ6Stop = 45
SD_AIO_Action_DAQ7Stop = 46
SD_AIO_Action_DAQ8Stop = 47
SD_AIO_Action_DAQ1Resume = 48
SD_AIO_Action_DAQ2Resume = 49
SD_AIO_Action_DAQ3Resume = 50
SD_AIO_Action_DAQ4Resume = 51
SD_AIO_Action_DAQ5Resume = 52
SD_AIO_Action_DAQ6Resume = 53
SD_AIO_Action_DAQ7Resume = 54
SD_AIO_Action_DAQ8Resume = 55
SD_AIO_Action_DAQ1Trigger = 56
SD_AIO_Action_DAQ2Trigger = 57
SD_AIO_Action_DAQ3Trigger = 58
SD_AIO_Action_DAQ4Trigger = 59
SD_AIO_Action_DAQ5Trigger = 60
SD_AIO_Action_DAQ6Trigger = 61
SD_AIO_Action_DAQ7Trigger = 62
SD_AIO_Action_DAQ8Trigger = 63
SD_AIO_Action_DAQ1Flush = 64
SD_AIO_Action_DAQ2Flush = 65
SD_AIO_Action_DAQ3Flush = 66
SD_AIO_Action_DAQ4Flush = 67
SD_AIO_Action_DAQ5Flush = 68
SD_AIO_Action_DAQ6Flush = 69
SD_AIO_Action_DAQ7Flush = 70
SD_AIO_Action_DAQ8Flush = 71
SD_AIO_Action_UserFpga0 = 72
SD_AIO_Action_UserFpga1 = 73
SD_AIO_Action_UserFpga2 = 74
SD_AIO_Action_UserFpga3 = 75
SD_AIO_Action_UserFpga4 = 76
SD_AIO_Action_UserFpga5 = 77
SD_AIO_Action_UserFpga6 = 78
SD_AIO_Action_UserFpga7 = 79
SD_AIO_Action_ApplyInstructions = 80
SD_AIO_Event_AWG1QueueEmpty = 0
SD_AIO_Event_AWG2QueueEmpty = 1
SD_AIO_Event_AWG3QueueEmpty = 2
SD_AIO_Event_AWG4QueueEmpty = 3
SD_AIO_Event_AWG1QueueFull = 4
SD_AIO_Event_AWG2QueueFull = 5
SD_AIO_Event_AWG3QueueFull = 6
SD_AIO_Event_AWG4QueueFull = 7
SD_AIO_Event_AWG1Underrun = 8
SD_AIO_Event_AWG2Underrun = 9
SD_AIO_Event_AWG3Underrun = 10
SD_AIO_Event_AWG4Underrun = 11
SD_AIO_Event_AWG1QueueEnd = 12
SD_AIO_Event_AWG2QueueEnd = 13
SD_AIO_Event_AWG3QueueEnd = 14
SD_AIO_Event_AWG4QueueEnd = 15
SD_AIO_Event_AWG1WfStart = 16
SD_AIO_Event_AWG2WfStart = 17
SD_AIO_Event_AWG3WfStart = 18
SD_AIO_Event_AWG4WfStart = 19
SD_AIO_Event_AWG1QueueMarker = 20
SD_AIO_Event_AWG2QueueMarker = 21
SD_AIO_Event_AWG3QueueMarker = 22
SD_AIO_Event_AWG4QueueMarker = 23
SD_AIO_Event_AWG1QueueFlushed = 24
SD_AIO_Event_AWG2QueueFlushed = 25
SD_AIO_Event_AWG3QueueFlushed = 26
SD_AIO_Event_AWG4QueueFlushed = 27
SD_AIO_Event_AWG1QueueRunning = 28
SD_AIO_Event_AWG2QueueRunning = 29
SD_AIO_Event_AWG3QueueRunning = 30
SD_AIO_Event_AWG4QueueRunning = 31
SD_AIO_Event_DAQ1Empty = 32
SD_AIO_Event_DAQ2Empty = 33
SD_AIO_Event_DAQ3Empty = 34
SD_AIO_Event_DAQ4Empty = 35
SD_AIO_Event_DAQ5Empty = 36
SD_AIO_Event_DAQ6Empty = 37
SD_AIO_Event_DAQ7Empty = 38
SD_AIO_Event_DAQ8Empty = 39
SD_AIO_Event_DAQ1Running = 40
SD_AIO_Event_DAQ2Running = 41
SD_AIO_Event_DAQ3Running = 42
SD_AIO_Event_DAQ4Running = 43
SD_AIO_Event_DAQ5Running = 44
SD_AIO_Event_DAQ6Running = 45
SD_AIO_Event_DAQ7Running = 46
SD_AIO_Event_DAQ8Running = 47
SD_AIO_Event_DAQ1TriggerLoopback = 48
SD_AIO_Event_DAQ2TriggerLoopback = 49
SD_AIO_Event_DAQ3TriggerLoopback = 50
SD_AIO_Event_DAQ4TriggerLoopback = 51
SD_AIO_Event_DAQ5TriggerLoopback = 52
SD_AIO_Event_DAQ6TriggerLoopback = 53
SD_AIO_Event_DAQ7TriggerLoopback = 54
SD_AIO_Event_DAQ8TriggerLoopback = 55
SD_AIO_Event_UserFpgaLoopback0 = 56
SD_AIO_Event_UserFpgaLoopback1 = 57
SD_AIO_Event_UserFpgaLoopback2 = 58
SD_AIO_Event_UserFpgaLoopback3 = 59
SD_AIO_Event_UserFpgaLoopback4 = 60
SD_AIO_Event_UserFpgaLoopback5 = 61
SD_AIO_Event_UserFpgaLoopback6 = 62
SD_AIO_Event_UserFpgaLoopback7 = 63
SD_AIO_Event_SandBoxPxiTrigger0 = 64
SD_AIO_Event_SandBoxPxiTrigger1 = 65
SD_AIO_Event_SandBoxPxiTrigger2 = 66
SD_AIO_Event_SandBoxPxiTrigger3 = 67
SD_AIO_Event_SandBoxPxiTrigger4 = 68
SD_AIO_Event_SandBoxPxiTrigger5 = 69
SD_AIO_Event_SandBoxPxiTrigger6 = 70
SD_AIO_Event_SandBoxPxiTrigger7 = 71
SD_AIO_Event_SandBoxFrontPanelTrigger0 = 72
SD_AIO_Event_AWG1TriggerLoopback = 73
SD_AIO_Event_AWG2TriggerLoopback = 74
SD_AIO_Event_AWG3TriggerLoopback = 75
SD_AIO_Event_AWG4TriggerLoopback = 76
SD_AIO_Event_SandBoxFrontPanelTrigger1 = 77
